// Auto-generated by scripts/sync_permissions.py
export const ItemPermissions = {
  CONFIG_AFFILIATE: "config:affiliate" as const,
  CONFIG_EXTERNAL_APIS: "config:external_apis" as const,
  CONFIG_FEDERATION: "config:federation" as const,
  CONFIG_INTERNAL: "config:internal" as const,
  DELETE_ITEM: "delete:item" as const,
  DELETE_MANIFESTATION: "delete:manifestation" as const,
  EDIT_COVER: "edit:cover" as const,
  LLM_GENERATE_CLOUD: "llm_generate:cloud" as const,
  LLM_GENERATE_COVER: "llm_generate:cover" as const,
  LLM_GENERATE_METADATA: "llm_generate:metadata" as const,
  READ_METADATA: "read:metadata" as const,
  READ_OWNERS: "read:owners" as const,
  READ_ROLES: "read:roles" as const,
  READ_USERS: "read:users" as const,
  REFETCH_METADATA: "refetch:metadata" as const,
  REGENERATE_COVER: "regenerate:cover" as const,
  UPDATE_ITEM: "update:item" as const,
  UPLOAD_COVER: "upload:cover" as const,
  WRITE_ITEM: "write:item" as const,
  WRITE_METADATA: "write:metadata" as const,
  WRITE_ROLES: "write:roles" as const,
  WRITE_USERS: "write:users" as const,
} as const;

export type ItemPermission = (typeof ItemPermissions)[keyof typeof ItemPermissions];
