// Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>
//

// THIS FILE IS AUTO-GENERATED by scripts/generate_taxonomy.py
// DO NOT EDIT MANUALLY. Update shared/taxonomy.yaml instead.

export const MEDIA_FORMATS = [
  "book",
  "graphic_novel",
  "comic_book",
  "magazine",
  "ebook",
  "audiobook_cd",
  "audiobook_cassette",
  "audiobook_digital",
  "cd",
  "vinyl",
  "sacd",
  "cassette",
  "minidisc",
  "cd_dvd_combo",
  "dvd",
  "bluray",
  "4k_uhd",
  "vcd",
  "vhs",
  "laserdisc",
  "board_game",
  "cards",
  "rpg_manual",
  "miniatures",
  "jigsaw_puzzle",
  "mechanical_puzzle",
] as const;
export type MediaFormat = (typeof MEDIA_FORMATS)[number];

export const MEDIA_CATEGORIES = ["text", "audiobook", "music", "movie", "board_game", "puzzle"] as const;
export type MediaCategory = (typeof MEDIA_CATEGORIES)[number];

export const MEDIA_HIERARCHY = {
  text: {
    label: "Text",
    default_image_type: "front",
    image_types: ["dust_jacket", "slipcase", "pages"],
    ui_icon: "Book",
    ui_aspect_ratio: 0.66666667,
    ui_parent: "book",
    formats: [
      {
        id: "book",
        label: "Book",
      },
      {
        id: "graphic_novel",
        label: "Graphic Novel / TPB",
      },
      {
        id: "comic_book",
        label: "Comic Book (Single Issue)",
      },
      {
        id: "magazine",
        label: "Magazine",
      },
      {
        id: "ebook",
        label: "eBook",
      },
    ],
  },
  audiobook: {
    label: "Audiobook",
    default_image_type: "front",
    image_types: ["disc", "cassette", "inlay", "slipcase"],
    ui_icon: "Headphones",
    ui_aspect_ratio: 1.0,
    ui_parent: "book",
    formats: [
      {
        id: "audiobook_cd",
        label: "Audiobook CD",
      },
      {
        id: "audiobook_cassette",
        label: "Audiobook Cassette",
        ui_aspect_ratio: 1.0,
      },
      {
        id: "audiobook_digital",
        label: "Digital Audiobook",
      },
    ],
  },
  music: {
    label: "Music",
    default_image_type: "disc",
    image_types: ["disc", "inlay", "vinyl_label", "gatefold", "obi", "booklet"],
    ui_icon: "Disc",
    ui_aspect_ratio: 1.0,
    ui_parent: null,
    formats: [
      {
        id: "cd",
        label: "CD",
      },
      {
        id: "vinyl",
        label: "Vinyl",
      },
      {
        id: "sacd",
        label: "SACD",
      },
      {
        id: "cassette",
        label: "Cassette",
      },
      {
        id: "minidisc",
        label: "MiniDisc",
      },
      {
        id: "cd_dvd_combo",
        label: "CD + DVD Edition",
      },
    ],
  },
  movie: {
    label: "Movie",
    default_image_type: "disc",
    image_types: ["disc", "inlay", "slipcover", "booklet"],
    ui_icon: "Film",
    ui_aspect_ratio: 1.5,
    ui_parent: null,
    formats: [
      {
        id: "dvd",
        label: "DVD",
      },
      {
        id: "bluray",
        label: "Blu-ray",
      },
      {
        id: "4k_uhd",
        label: "4K UHD",
      },
      {
        id: "vcd",
        label: "Video CD (VCD)",
        ui_aspect_ratio: 1.0,
      },
      {
        id: "vhs",
        label: "VHS",
      },
      {
        id: "laserdisc",
        label: "LaserDisc",
        ui_aspect_ratio: 1.0,
      },
    ],
  },
  board_game: {
    label: "Board Game",
    default_image_type: "box",
    image_types: ["box", "board", "components", "rulebook"],
    ui_icon: "Dices",
    ui_aspect_ratio: 1.0,
    ui_parent: null,
    formats: [
      {
        id: "board_game",
        label: "Board Game",
      },
      {
        id: "cards",
        label: "Card Game",
      },
      {
        id: "rpg_manual",
        label: "RPG Manual",
        ui_aspect_ratio: 0.66666667,
      },
      {
        id: "miniatures",
        label: "Miniatures / Wargame",
      },
    ],
  },
  puzzle: {
    label: "Puzzle",
    default_image_type: "box",
    image_types: ["pieces", "completed_puzzle", "poster"],
    ui_icon: "Puzzle",
    ui_aspect_ratio: 1.0,
    ui_parent: null,
    formats: [
      {
        id: "jigsaw_puzzle",
        label: "Jigsaw Puzzle",
      },
      {
        id: "mechanical_puzzle",
        label: "Mechanical / 3D Puzzle",
      },
    ],
  },
} as const;

export const CATEGORY_STATUS_MAP = {
  text: ["want_to_read", "reading", "read", "dnf"],
  audiobook: ["want_to_listen", "listening", "listened", "dnf"],
  music: ["want_to_listen", "listened"],
  movie: ["want_to_watch", "watched", "dnf"],
  board_game: ["want_to_play", "playing", "played"],
  puzzle: ["want_to_play", "playing", "played"],
} as const;

export const SCAN_FORMATS = ["book", "audiobook", "music", "movie", "board_game", "puzzle"] as const;
export type ScanFormat = (typeof SCAN_FORMATS)[number];

export const GLOBAL_IMAGE_TYPES = ["front", "back", "spine", "other"] as const;
export const CATEGORY_IMAGE_TYPES = {
  text: ["dust_jacket", "slipcase", "pages"],
  audiobook: ["disc", "cassette", "inlay", "slipcase"],
  music: ["disc", "inlay", "vinyl_label", "gatefold", "obi", "booklet"],
  movie: ["disc", "inlay", "slipcover", "booklet"],
  board_game: ["box", "board", "components", "rulebook"],
  puzzle: ["pieces", "completed_puzzle", "poster"],
} as const;

export const CATEGORY_DEFAULT_IMAGE_TYPE: Record<MediaCategory, string> = {
  text: "front",
  audiobook: "front",
  music: "disc",
  movie: "disc",
  board_game: "box",
  puzzle: "box",
};

export const FORMAT_ALIAS_TO_CATEGORY: Record<string, MediaCategory> = {
  book: "text",
  graphic_novel: "text",
  comic_book: "text",
  magazine: "text",
  ebook: "text",
  audiobook_cd: "audiobook",
  audiobook_cassette: "audiobook",
  audiobook_digital: "audiobook",
  cd: "music",
  vinyl: "music",
  sacd: "music",
  cassette: "music",
  minidisc: "music",
  cd_dvd_combo: "music",
  dvd: "movie",
  bluray: "movie",
  "4k_uhd": "movie",
  vcd: "movie",
  vhs: "movie",
  laserdisc: "movie",
  board_game: "board_game",
  cards: "board_game",
  rpg_manual: "board_game",
  miniatures: "board_game",
  jigsaw_puzzle: "puzzle",
  mechanical_puzzle: "puzzle",
  standard: "text",
  audio: "music",
  sound: "music",
  lp: "music",
  video: "movie",
  "moving image": "movie",
  game: "board_game",
  boardgame: "board_game",
  "three-dimensional object": "board_game",
};

export type CollectionStatus = "available" | "damaged" | "lent" | "lost" | "ordered" | "wish_list";

export type ProgressStatus =
  | "dnf"
  | "listened"
  | "listening"
  | "played"
  | "playing"
  | "read"
  | "reading"
  | "want_to_listen"
  | "want_to_play"
  | "want_to_read"
  | "want_to_watch"
  | "watched";

export type ImageType =
  | "back"
  | "board"
  | "booklet"
  | "box"
  | "cassette"
  | "completed_puzzle"
  | "components"
  | "disc"
  | "dust_jacket"
  | "front"
  | "gatefold"
  | "inlay"
  | "obi"
  | "other"
  | "pages"
  | "pieces"
  | "poster"
  | "rulebook"
  | "slipcase"
  | "slipcover"
  | "spine"
  | "vinyl_label";
