# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""Parity tests for the dependency-light perceptual hash.

``app/utils/phash.py`` replaced ``imagehash`` so the production image would not
need ``numpy`` and ``scipy`` (167 MB). These hashes are *persisted* in
``IQOQO_KNOWN_JUNK_PHASHES``, so a silent one-bit drift would not raise -- it
would just stop every stored hash from matching and quietly turn cover
de-duplication off. The expected values below are therefore literals captured
from ``imagehash.phash()`` itself (imagehash 4.3.2, with its pinned scipy and
numpy), not values regenerated by the code under test.

The one documented exception is :data:`TIE_CORPUS_HASHES`, covering inputs whose
DCT block has coefficients exactly tied at the median. See its comment.
"""

import subprocess
import sys

import pytest

from app.utils.phash import HASH_HEX_WIDTH, parse_hash, perceptual_hash
from tests.phash_corpus import build_corpus, tie_corpus

# Captured from imagehash.phash() (imagehash 4.3.2) over the corpus built by
# tests/phash_corpus.py:build_corpus(). Regenerate with the one-off recipe in
# the module docstring only if the algorithm changes deliberately -- an
# accidental drift is the bug these tests exist to catch.
IMAGEHASH_GOLDEN = {
    "cover_art_0": "91cc1e4b08557df9",
    "cover_art_0_rotated": "85cd250b2dbc5f32",
    "cover_art_0_flipped": "c49b4f1e5d2528ad",
    "cover_art_0_scaled": "91cc1e4b08557df9",
    "cover_art_1": "81972b5e1ff03d48",
    "cover_art_1_rotated": "80d50f3f5eb23cc2",
    "cover_art_1_flipped": "d4c27e0b4ab5691d",
    "cover_art_1_scaled": "81972b5e1ff03d48",
    "cover_art_2": "c0f06f1f07ae390e",
    "cover_art_2_rotated": "d0f74e1b0630379d",
    "cover_art_2_flipped": "95253a4a567b6c53",
    "cover_art_2_scaled": "c0f06f1f07ae390e",
    "cover_art_3": "904d2b0f5de8b745",
    "cover_art_3_rotated": "945d033e7f682da1",
    "cover_art_3_flipped": "c5187f5a09bde710",
    "cover_art_3_scaled": "904d2b0f5de8b745",
    "cover_photo_0": "bc5ab9c1c3c4e853",
    "cover_photo_0_gray": "bc5ab9c1c3c4e853",
    "cover_photo_0_palette": "bc5aa9c1c3c4e85b",
    "cover_photo_0_rotated": "851f51a84f0e1fb5",
    "cover_photo_1": "f00db06c1ee81fe9",
    "cover_photo_1_gray": "f00db06c1ee81fe9",
    "cover_photo_1_palette": "f00fb0681ff01fe8",
    "cover_photo_1_rotated": "851d453c4fbc4ab5",
    "cover_photo_2": "90664b9f66c96297",
    "cover_photo_2_gray": "90664b9f66c96297",
    "cover_photo_2_palette": "90664b9f66c96297",
    "cover_photo_2_rotated": "907d459a4e940f7e",
    "cover_photo_3": "eb9448b3cc4cb36c",
    "cover_photo_3_gray": "eb9448b3cc4cb36c",
    "cover_photo_3_palette": "eb9448b3dc48b566",
    "cover_photo_3_rotated": "d0bd45360b085fbe",
    "cover_gray_ramp": "8000800080008000",
    "cover_gray_ramp_wide": "8000000000000000",
    "cover_color_ramp": "aa00000000000000",
    "placeholder_plate_light": "9f1ee0e01f1fe0e0",
    "placeholder_plate_dark": "e0e01f1fe0e01f1f",
    "placeholder_plate_branded": "e0e01f1fe0e01f1f",
    "placeholder_plate_blurred": "9f1ee0e01f1fe0e0",
    "placeholder_flat_0": "0000000000000000",
    "placeholder_flat_1": "8000000000000000",
    "placeholder_flat_17": "8000000000000000",
    "placeholder_flat_128": "8000000000000000",
    "placeholder_flat_254": "8000000000000000",
    "placeholder_flat_255": "8000000000000000",
    "placeholder_flat_hue": "8000000000000000",
    "placeholder_icon": "80002a002a002a00",
    "edge_single_pixel": "8000000000000000",
    "edge_wide_strip": "8000000000000000",
    "edge_tall_strip": "8000000000000000",
    "edge_hairline": "8000000000000000",
    "edge_mode_l": "8000000000000000",
    "edge_mode_rgba": "8000000000000000",
    "edge_mode_cmyk": "8000000000000000",
    "edge_mode_16bit": "8000000000000000",
}

# The one class where byte-identity with imagehash is not reproducible, and why.
#
# A 32-point DCT of a symmetric input produces coefficients that are *bit-for-bit
# equal*, and when the 32nd and 33rd smallest of the 64 collide the median is one
# of those values. imagehash thresholded with `>` against a median its own FFT
# had perturbed by ~1e-16 relative, so which tied coefficients came out as 1 was
# decided by rounding, not arithmetic. Measured over 3000 randomised images, 8
# diverged - all exact ties; no other input class did. Reproducing them would mean
# reproducing scipy's floating-point operation order, which is neither possible
# in general nor worth coupling to. This implementation instead returns the
# mathematically correct answer (a tie is not greater than the median, so 0).
#
# Both halves are pinned: our value, and what imagehash produced. KNOWN_DIVERGENCES
# names the inputs where the two differ, so a change that widens the
# incompatibility fails the suite instead of quietly reaching production.
TIE_CORPUS_HASHES = {
    "tie_cross": ("e6a2b3194ca6b319", "e6a2b3194ce6b319"),
    "tie_horizontal_ramp": ("8000000000000000", "8000000000000000"),
    "tie_two_tone": ("8080000000800000", "8080000000800000"),
}

KNOWN_DIVERGENCES = frozenset({"tie_cross"})


def test_golden_table_covers_the_whole_corpus():
    """A renamed or dropped fixture must not silently shrink the assertions."""
    assert set(IMAGEHASH_GOLDEN) == set(build_corpus())


def test_tie_table_covers_the_whole_tie_corpus():
    assert set(TIE_CORPUS_HASHES) == set(tie_corpus())


def test_golden_table_is_well_formed():
    """Every expected value is a full-width lowercase hex string."""
    for name, expected in IMAGEHASH_GOLDEN.items():
        assert parse_hash(expected) == expected, name
    for name, (ours, theirs) in TIE_CORPUS_HASHES.items():
        assert parse_hash(ours) == ours, name
        assert parse_hash(theirs) == theirs, name


@pytest.mark.parametrize("name", sorted(IMAGEHASH_GOLDEN))
def test_matches_imagehash_byte_for_byte(name):
    """Every corpus entry reproduces the hash imagehash produced for it."""
    assert perceptual_hash(build_corpus()[name]) == IMAGEHASH_GOLDEN[name]


@pytest.mark.parametrize("name", sorted(TIE_CORPUS_HASHES))
def test_tie_inputs_are_deterministic(name):
    """Exact-tie inputs stay stable across runs and repeated calls."""
    image = tie_corpus()[name]
    expected = TIE_CORPUS_HASHES[name][0]
    assert perceptual_hash(image) == expected
    assert {perceptual_hash(image) for _ in range(5)} == {expected}


def test_tie_divergence_is_confined_to_the_documented_set():
    """Pin the *scope* of the one known incompatibility.

    Two of the three tie inputs still agree with imagehash; only a perfectly
    symmetric cross does not. If a future change widens that set, the honest
    response is to update this list and the docs, not to let it drift unnoticed.
    """
    corpus = tie_corpus()
    divergent = {name for name, (ours, theirs) in TIE_CORPUS_HASHES.items() if ours != theirs and perceptual_hash(corpus[name]) == ours}
    assert divergent == KNOWN_DIVERGENCES


def test_hash_shape_is_fixed_width():
    """All corpus hashes are HASH_HEX_WIDTH hex chars, whatever the input."""
    for image in list(build_corpus().values()) + list(tie_corpus().values()):
        result = perceptual_hash(image)
        assert len(result) == HASH_HEX_WIDTH, result
        assert result == result.lower()


def test_flat_colour_hashes_are_stable_and_distinct_from_structure():
    """The degenerate flat case still yields the canonical all-DC bit pattern."""
    corpus = build_corpus()
    assert perceptual_hash(corpus["placeholder_flat_0"]) == "0000000000000000"
    for level in (1, 17, 128, 254, 255):
        assert perceptual_hash(corpus[f"placeholder_flat_{level}"]) == "8000000000000000"


def test_scaling_a_cover_does_not_change_its_hash():
    """Perceptual hashing's whole purpose: resizing must not change identity.

    Lanczos resampling means an exact resize *can* shift a borderline
    coefficient, so this asserts the property on artwork with clear structure
    rather than on every corpus entry.
    """
    corpus = build_corpus()
    for seed in range(4):
        assert perceptual_hash(corpus[f"cover_art_{seed}_scaled"]) == perceptual_hash(corpus[f"cover_art_{seed}"])


def test_duplicate_detection_is_exact_for_identical_covers():
    """The feature itself: two copies of the same cover must collide, and a
    different cover must not."""
    corpus = build_corpus()
    for seed in range(4):
        art = corpus[f"cover_art_{seed}"]
        assert perceptual_hash(art) == perceptual_hash(art.copy())
    distinct = {perceptual_hash(corpus[f"cover_art_{seed}"]) for seed in range(4)}
    assert len(distinct) == 4, "distinct artwork collided"


def test_module_does_not_import_numpy_or_scipy():
    """The whole point of the module: no numerical-library dependency.

    Probed on ``app.utils.images`` -- the real consumer -- rather than on
    ``app.utils.phash`` alone, because a future transitive import through the
    app package would reintroduce the dependency just as effectively. Run in a
    fresh interpreter because the pytest session itself has numpy loaded by
    other tests and would mask a regression here.
    """
    probe = (
        "import sys; import app.utils.images; "
        "loaded = sorted(m for m in sys.modules if m.split('.')[0] in {'numpy', 'scipy', 'imagehash'}); "
        "print(','.join(loaded))"
    )
    result = subprocess.run([sys.executable, "-c", probe], capture_output=True, text=True, check=True)
    assert result.stdout.strip() == "", f"the cover path pulled in {result.stdout.strip()}"


def test_parse_hash_normalises_case_and_whitespace():
    """Operators paste these out of logs and admin UI, so be forgiving."""
    assert parse_hash("  91CC1E4B08557DF9  ") == "91cc1e4b08557df9"
    assert parse_hash("e1e1e1e1e1e1e1e1") == "e1e1e1e1e1e1e1e1"


@pytest.mark.parametrize("bad", ["", "abc", "91cc1e4b08557df", "91cc1e4b08557df99", "zzcc1e4b08557df9", "0x1234567890abcdef"])
def test_parse_hash_rejects_anything_that_is_not_a_phash(bad):
    """Malformed entries are refused, not silently reinterpreted.

    imagehash.hex_to_hash inferred the hash shape from the string length, so a
    short value quietly dropped its high bits and a long one raised a ragged
    array error. Only exactly 16 hex digits ever worked, and that is the only
    case accepted now.
    """
    with pytest.raises(ValueError):
        parse_hash(bad)


def test_configured_known_junk_hashes_still_parse():
    """The hashes shipped in .env / .env.example must survive the parser."""
    for configured in ("e1e1e1e1e1e1e1e1", "ffffffff00000000", "eea4985b94846fe8"):
        assert parse_hash(configured) == configured
