# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  redis:
    endpoint: "redis:6379"
    collection_interval: 10s
  postgresql:
    endpoint: "db:5432"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    databases:
      - "${POSTGRES_DB}"
    collection_interval: 10s
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 10s
    env_vars_to_metric_labels:
      - COMPOSE_SERVICE

processors:
  batch:
    send_batch_size: 8192
    timeout: 5s
    send_batch_max_size: 10240

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "iqoqo"

service:
  pipelines:
    metrics:
      receivers: [otlp, redis, postgresql, docker_stats]
      processors: [batch]
      exporters: [prometheus]
