"""Add instance_settings table

Revision ID: 012982fb9fe5
Revises: 2973a4475ace
Create Date: 2026-03-14 01:23:11.299857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012982fb9fe5'
down_revision = '2973a4475ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_settings_key'))

    op.drop_table('instance_settings')
    # ### end Alembic commands ###
