"""Add instance_settings table

Revision ID: 012982fb9fe5
Revises: 2973a4475ace
Create Date: 2026-03-14 01:23:11.299857

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "012982fb9fe5"
down_revision = "2973a4475ace"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instance_settings_key"), ["key"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_settings_key"))

    op.drop_table("instance_settings")
    # ### end Alembic commands ###
