"""Harden LLMTelemetry and ContainerAggregation models

Revision ID: 08ac7a22bd8c
Revises: 40408803b0ba
Create Date: 2026-04-04 11:08:44.266365

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '08ac7a22bd8c'
down_revision = '40408803b0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_telemetry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_provider_user_op_time'), type_='unique')
        batch_op.create_index('ix_llm_telemetry_provider_user_op_time', ['provider', 'user_id', 'operation_type', 'created_at'], unique=False)

    with op.batch_alter_table('container_aggregations', schema='catalog') as batch_op:
        batch_op.create_check_constraint(
            'ck_container_aggregation_type_match',
            "(aggregated_type = 'work' AND aggregated_work_id IS NOT NULL AND aggregated_item_id IS NULL) OR "
            "(aggregated_type = 'item' AND aggregated_item_id IS NOT NULL AND aggregated_work_id IS NULL)"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_telemetry', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_provider_user_op_time'), ['provider', 'user_id', 'operation_type', 'created_at'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('container_aggregations', schema='catalog') as batch_op:
        batch_op.drop_constraint('ck_container_aggregation_type_match', type_='check')

    # ### end Alembic commands ###
