# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""Harden LLMTelemetry and ContainerAggregation models

Revision ID: 08ac7a22bd8c
Revises: 40408803b0ba
Create Date: 2026-04-04 11:08:44.266365

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "08ac7a22bd8c"
down_revision = "40408803b0ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import sqlalchemy as sa

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def has_unique_constraint(table_name, constraint_name, schema=None):
        constraints = inspector.get_unique_constraints(table_name, schema=schema)
        return any(c["name"] == constraint_name for c in constraints)

    def has_index(table_name, index_name, schema=None):
        indexes = inspector.get_indexes(table_name, schema=schema)
        return any(idx["name"] == index_name for idx in indexes)

    def has_check_constraint(table_name, constraint_name, schema=None):
        try:
            constraints = inspector.get_check_constraints(table_name, schema=schema)
            return any(c["name"] == constraint_name for c in constraints)
        except Exception:
            return False

    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        if has_unique_constraint("llm_telemetry", "uq_provider_user_op_time", schema=None):
            batch_op.drop_constraint(batch_op.f("uq_provider_user_op_time"), type_="unique")
        if not has_index("llm_telemetry", "ix_llm_telemetry_provider_user_op_time", schema=None):
            batch_op.create_index(
                "ix_llm_telemetry_provider_user_op_time", ["provider", "user_id", "operation_type", "created_at"], unique=False
            )

    with op.batch_alter_table("container_aggregations", schema="catalog") as batch_op:
        if not has_check_constraint("container_aggregations", "ck_container_aggregation_type_match", schema="catalog"):
            batch_op.create_check_constraint(
                "ck_container_aggregation_type_match",
                "(aggregated_type = 'work' AND aggregated_work_id IS NOT NULL AND aggregated_item_id IS NULL) OR "
                "(aggregated_type = 'item' AND aggregated_item_id IS NOT NULL AND aggregated_work_id IS NULL)",
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_provider_user_op_time"),
            ["provider", "user_id", "operation_type", "created_at"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("container_aggregations", schema="catalog") as batch_op:
        batch_op.drop_constraint("ck_container_aggregation_type_match", type_="check")

    # ### end Alembic commands ###
