"""Initial migration.

Revision ID: 0a9010ed74e4
Revises:
Create Date: 2026-01-11 00:32:11.734524

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0a9010ed74e4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # type: ignore
        "works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expressions",  # type: ignore
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manifestations",  # type: ignore
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expression_id", sa.Integer(), nullable=False),
        sa.Column("isbn13", sa.String(length=13), nullable=True),
        sa.Column("upc", sa.String(length=12), nullable=True),
        sa.Column("ean", sa.String(length=13), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["expression_id"],
            ["expressions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_manifestations_ean"), ["ean"], unique=False)
        batch_op.create_index(batch_op.f("ix_manifestations_isbn13"), ["isbn13"], unique=True)
        batch_op.create_index(batch_op.f("ix_manifestations_upc"), ["upc"], unique=False)

    op.create_table(
        "items",  # type: ignore
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manifestation_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["manifestation_id"],
            ["manifestations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manifestations_upc"))
        batch_op.drop_index(batch_op.f("ix_manifestations_isbn13"))
        batch_op.drop_index(batch_op.f("ix_manifestations_ean"))

    op.drop_table("manifestations")
    op.drop_table("expressions")
    op.drop_table("works")
    # ### end Alembic commands ###
