"""add metadata_refetch_log

Revision ID: 0c3eaee0322b
Revises: 839197bcbabc
Create Date: 2026-07-17 14:56:59.904532

"""
# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3eaee0322b'
down_revision = '839197bcbabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_refetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('iqoqo_version', sa.String(length=50), nullable=False),
    sa.Column('found_fields', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'strategy', name='uq_metadata_refetch_log'),
    schema='inventory'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_refetch_log', schema='inventory')
    # ### end Alembic commands ###
