"""add metadata_refetch_log

Revision ID: 0c3eaee0322b
Revises: 839197bcbabc
Create Date: 2026-07-17 14:56:59.904532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3eaee0322b'
down_revision = '839197bcbabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_refetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('iqoqo_version', sa.String(length=50), nullable=False),
    sa.Column('found_fields', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'strategy', name='uq_metadata_refetch_log'),
    schema='inventory'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_refetch_log', schema='inventory')
    # ### end Alembic commands ###
