# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""Add UserCollection and Tag taxonomy models

Revision ID: 1b7b2d612e23
Revises: 070_social_sharing
Create Date: 2026-05-18 22:59:55.553030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1b7b2d612e23"
down_revision = "070_social_sharing"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="catalog",
    )
    with op.batch_alter_table("tags", schema="catalog") as batch_op:
        batch_op.create_index(batch_op.f("ix_catalog_tags_name"), ["name"], unique=True)

    op.create_table(
        "user_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["inventory.user_collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    with op.batch_alter_table("user_collections", schema="inventory") as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_user_collections_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_user_collections_parent_id"), ["parent_id"], unique=False)

    op.create_table(
        "item_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("added_by_id", sa.UUID(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["added_by_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["item_id"], ["inventory.items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["catalog.tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    with op.batch_alter_table("item_tags", schema="inventory") as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_item_tags_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_item_tags_tag_id"), ["tag_id"], unique=False)

    op.create_table(
        "user_collection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["collection_id"], ["inventory.user_collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["inventory.items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    with op.batch_alter_table("user_collection_items", schema="inventory") as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_user_collection_items_collection_id"), ["collection_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_user_collection_items_item_id"), ["item_id"], unique=False)

    op.drop_table("item_status_logs")
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_settings_key"))

    op.drop_table("instance_settings")
    op.drop_table("user_roles")
    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_works_fts"), postgresql_using="gin")
        batch_op.drop_index(batch_op.f("ix_works_search_vector"), postgresql_using="gin")

    op.drop_table("works")
    op.drop_table("shared_collections")
    with op.batch_alter_table("work_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_parts_container_work_id"))
        batch_op.drop_index(batch_op.f("ix_work_parts_part_work_id"))

    op.drop_table("work_parts")
    op.drop_table("expressions")
    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_telemetry_provider_user_op_time"))

    op.drop_table("llm_telemetry")
    with op.batch_alter_table("manifestation_contributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manifestation_contributions_contributor_id"))
        batch_op.drop_index(batch_op.f("ix_manifestation_contributions_manifestation_id"))

    op.drop_table("manifestation_contributions")
    with op.batch_alter_table("scan_telemetry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_telemetry_barcode"))

    op.drop_table("scan_telemetry")
    op.drop_table("image_scans")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_name"))

    op.drop_table("permissions")
    op.drop_table("role_permissions")
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manifestations_ean"))
        batch_op.drop_index(batch_op.f("ix_manifestations_fts"), postgresql_using="gin")
        batch_op.drop_index(batch_op.f("ix_manifestations_isbn13"))
        batch_op.drop_index(batch_op.f("ix_manifestations_upc"))

    op.drop_table("manifestations")
    with op.batch_alter_table("user_consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_consents_consent_type"))

    op.drop_table("user_consents")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_lent_to_user_id"))
        batch_op.drop_index(batch_op.f("ix_items_owner_id"))

    op.drop_table("items")
    with op.batch_alter_table("expression_contributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expression_contributions_contributor_id"))
        batch_op.drop_index(batch_op.f("ix_expression_contributions_expression_id"))

    op.drop_table("expression_contributions")
    with op.batch_alter_table("work_contributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_contributions_contributor_id"))
        batch_op.drop_index(batch_op.f("ix_work_contributions_work_id"))

    op.drop_table("work_contributions")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))

    op.drop_table("roles")
    with op.batch_alter_table("token_blocklist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_blocklist_jti"))

    op.drop_table("token_blocklist")
    with op.batch_alter_table("container_aggregations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_container_aggregations_container_work_id"))

    op.drop_table("container_aggregations")
    with op.batch_alter_table("contributors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contributors_name"))

    op.drop_table("contributors")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_public_username"))

    op.drop_table("users")
    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_public_visibility"))
        batch_op.drop_constraint(batch_op.f("uq_users_public_username"), type_="unique")
        batch_op.create_index(batch_op.f("ix_auth_users_public_username"), ["public_username"], unique=True)

    with op.batch_alter_table("expressions", schema="catalog") as batch_op:
        batch_op.drop_constraint(batch_op.f("expressions_work_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "works", ["work_id"], ["id"], referent_schema="catalog", ondelete="CASCADE")

    with op.batch_alter_table("instance_settings", schema="catalog") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False, autoincrement=True)

    with op.batch_alter_table("manifestations", schema="catalog") as batch_op:
        batch_op.drop_constraint(batch_op.f("manifestations_expression_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "expressions", ["expression_id"], ["id"], referent_schema="catalog", ondelete="CASCADE")

    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.alter_column("is_hidden", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
        batch_op.drop_index(batch_op.f("ix_items_owner_hidden"))
        batch_op.drop_constraint(batch_op.f("items_manifestation_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "manifestations", ["manifestation_id"], ["id"], referent_schema="catalog", ondelete="CASCADE")

    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False, autoincrement=True)

    with op.batch_alter_table("scan_telemetry", schema="inventory") as batch_op:
        batch_op.drop_constraint(batch_op.f("scan_telemetry_manifestation_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "manifestations", ["manifestation_id"], ["id"], referent_schema="catalog", ondelete="SET NULL")

    with op.batch_alter_table("shared_collections", schema="inventory") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=None, existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_collections", schema="inventory") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=sa.text("now()"), existing_nullable=True)

    with op.batch_alter_table("scan_telemetry", schema="inventory") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("scan_telemetry_manifestation_id_fkey"), "manifestations", ["manifestation_id"], ["id"], referent_schema="catalog"
        )

    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("items_manifestation_id_fkey"), "manifestations", ["manifestation_id"], ["id"], referent_schema="catalog"
        )
        batch_op.create_index(batch_op.f("ix_items_owner_hidden"), ["owner_id", "is_hidden"], unique=False)
        batch_op.alter_column("is_hidden", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)

    with op.batch_alter_table("manifestations", schema="catalog") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("manifestations_expression_id_fkey"), "expressions", ["expression_id"], ["id"], referent_schema="catalog"
        )

    with op.batch_alter_table("instance_settings", schema="catalog") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("expressions", schema="catalog") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(batch_op.f("expressions_work_id_fkey"), "works", ["work_id"], ["id"], referent_schema="catalog")

    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_users_public_username"))
        batch_op.create_unique_constraint(batch_op.f("uq_users_public_username"), ["public_username"], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f("ix_users_public_visibility"), ["public_username", "visibility"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("display_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("public_username", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("bio", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("avatar_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("google_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("visibility", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("google_id", name=op.f("users_google_id_key"), postgresql_include=[], postgresql_nulls_not_distinct=False),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_public_username"), ["public_username"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "contributors",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("meta", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("contributors_pkey")),
        sa.UniqueConstraint(
            "name", "type", name=op.f("uq_contributor_name_type"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    with op.batch_alter_table("contributors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contributors_name"), ["name"], unique=False)

    op.create_table(
        "container_aggregations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("container_work_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("aggregated_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("aggregated_work_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("aggregated_item_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("component_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "aggregated_type::text = 'work'::text AND aggregated_work_id IS NOT NULL AND aggregated_item_id IS NULL OR aggregated_type::text = 'item'::text AND aggregated_item_id IS NOT NULL AND aggregated_work_id IS NULL",
            name=op.f("ck_container_aggregation_type_match"),
        ),
        sa.ForeignKeyConstraint(
            ["aggregated_item_id"], ["items.id"], name=op.f("container_aggregations_aggregated_item_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["aggregated_work_id"], ["works.id"], name=op.f("container_aggregations_aggregated_work_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["container_work_id"], ["works.id"], name=op.f("container_aggregations_container_work_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("container_aggregations_pkey")),
    )
    with op.batch_alter_table("container_aggregations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_container_aggregations_container_work_id"), ["container_work_id"], unique=False)

    op.create_table(
        "token_blocklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blocklist_pkey")),
    )
    with op.batch_alter_table("token_blocklist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_token_blocklist_jti"), ["jti"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)

    op.create_table(
        "work_contributions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("work_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contributor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("sequence", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["contributor_id"], ["contributors.id"], name=op.f("work_contributions_contributor_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], name=op.f("work_contributions_work_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("work_contributions_pkey")),
    )
    with op.batch_alter_table("work_contributions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_work_contributions_work_id"), ["work_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_work_contributions_contributor_id"), ["contributor_id"], unique=False)

    op.create_table(
        "expression_contributions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("expression_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contributor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("sequence", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["contributor_id"], ["contributors.id"], name=op.f("expression_contributions_contributor_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["expression_id"], ["expressions.id"], name=op.f("expression_contributions_expression_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("expression_contributions_pkey")),
    )
    with op.batch_alter_table("expression_contributions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expression_contributions_expression_id"), ["expression_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_expression_contributions_contributor_id"), ["contributor_id"], unique=False)

    op.create_table(
        "items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("manifestation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("collection_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("condition", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("lent_to_user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("lent_to_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("is_hidden", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("added_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("meta", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["lent_to_user_id"], ["users.id"], name=op.f("items_lent_to_user_id_fkey"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manifestation_id"], ["manifestations.id"], name=op.f("items_manifestation_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("items_owner_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("items_pkey")),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_lent_to_user_id"), ["lent_to_user_id"], unique=False)

    op.create_table(
        "user_consents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("consent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("is_granted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("policy_version", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_consents_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("user_consents_pkey")),
    )
    with op.batch_alter_table("user_consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_consents_consent_type"), ["consent_type"], unique=False)

    op.create_table(
        "manifestations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("expression_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("isbn13", sa.VARCHAR(length=13), autoincrement=False, nullable=True),
        sa.Column("upc", sa.VARCHAR(length=12), autoincrement=False, nullable=True),
        sa.Column("ean", sa.VARCHAR(length=13), autoincrement=False, nullable=True),
        sa.Column("publisher", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("publication_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("cover_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("meta", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("fts_simple", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["expression_id"], ["expressions.id"], name=op.f("manifestations_expression_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("manifestations_pkey")),
    )
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_manifestations_upc"), ["upc"], unique=False)
        batch_op.create_index(batch_op.f("ix_manifestations_isbn13"), ["isbn13"], unique=True)
        batch_op.create_index(batch_op.f("ix_manifestations_fts"), ["fts_simple"], unique=False, postgresql_using="gin")
        batch_op.create_index(batch_op.f("ix_manifestations_ean"), ["ean"], unique=False)

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], name=op.f("role_permissions_permission_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("role_permissions_role_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("role_permissions_pkey")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("permissions_pkey")),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permissions_name"), ["name"], unique=True)

    op.create_table(
        "image_scans",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("manifestation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("scan_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("source", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["manifestation_id"], ["manifestations.id"], name=op.f("image_scans_manifestation_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("image_scans_pkey")),
    )
    op.create_table(
        "scan_telemetry",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("barcode", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("format_hint", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("provider", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("manifestation_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("raw_request_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["manifestation_id"], ["manifestations.id"], name=op.f("scan_telemetry_manifestation_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scan_telemetry_pkey")),
    )
    with op.batch_alter_table("scan_telemetry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_telemetry_barcode"), ["barcode"], unique=False)

    op.create_table(
        "manifestation_contributions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("manifestation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contributor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("sequence", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["contributor_id"], ["contributors.id"], name=op.f("manifestation_contributions_contributor_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["manifestation_id"], ["manifestations.id"], name=op.f("manifestation_contributions_manifestation_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("manifestation_contributions_pkey")),
    )
    with op.batch_alter_table("manifestation_contributions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_manifestation_contributions_manifestation_id"), ["manifestation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_manifestation_contributions_contributor_id"), ["contributor_id"], unique=False)

    op.create_table(
        "llm_telemetry",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("operation_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("images_generated", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("estimated_cost_usd", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("total_duration_seconds", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("llm_telemetry_pkey")),
    )
    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_telemetry_provider_user_op_time"), ["provider", "user_id", "operation_type", "created_at"], unique=False
        )

    op.create_table(
        "expressions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("work_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("meta", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], name=op.f("expressions_work_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("expressions_pkey")),
    )
    op.create_table(
        "work_parts",
        sa.Column("container_work_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("part_work_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sequence", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["container_work_id"], ["works.id"], name=op.f("work_parts_container_work_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["part_work_id"], ["works.id"], name=op.f("work_parts_part_work_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("container_work_id", "part_work_id", name=op.f("work_parts_pkey")),
    )
    with op.batch_alter_table("work_parts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_work_parts_part_work_id"), ["part_work_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_work_parts_container_work_id"), ["container_work_id"], unique=False)

    op.create_table(
        "shared_collections",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("share_token", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "filters", postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("shared_collections_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("shared_collections_pkey")),
        sa.UniqueConstraint(
            "share_token", name=op.f("shared_collections_share_token_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    op.create_table(
        "works",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("meta", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("fts_simple", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("works_pkey")),
    )
    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_works_search_vector"), ["search_vector"], unique=False, postgresql_using="gin")
        batch_op.create_index(batch_op.f("ix_works_fts"), ["fts_simple"], unique=False, postgresql_using="gin")

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("user_roles_role_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_roles_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("user_roles_pkey")),
    )
    op.create_table(
        "instance_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("key", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("value", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("instance_settings_pkey")),
    )
    with op.batch_alter_table("instance_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instance_settings_key"), ["key"], unique=True)

    op.create_table(
        "item_status_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("old_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("new_status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("changed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], name=op.f("item_status_logs_item_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("item_status_logs_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("item_status_logs_pkey")),
    )
    with op.batch_alter_table("user_collection_items", schema="inventory") as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_user_collection_items_item_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_user_collection_items_collection_id"))

    op.drop_table("user_collection_items", schema="inventory")
    with op.batch_alter_table("item_tags", schema="inventory") as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_item_tags_tag_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_item_tags_item_id"))

    op.drop_table("item_tags", schema="inventory")
    with op.batch_alter_table("user_collections", schema="inventory") as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_user_collections_parent_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_user_collections_owner_id"))

    op.drop_table("user_collections", schema="inventory")
    with op.batch_alter_table("tags", schema="catalog") as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_tags_name"))

    op.drop_table("tags", schema="catalog")
    # ### end Alembic commands ###
