"""Add cover path and telemetry

Revision ID: 20260228_add_cover
Revises:
Create Date: 2026-02-28 12:00:00.000000

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260228_add_cover"
down_revision = "c3d8e1f20a45"


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "llm_telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("images_generated", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cover_path", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.drop_column("cover_path")

    op.drop_table("llm_telemetry")
    # ### end Alembic commands ###
