"""Add cover path and telemetry

Revision ID: 20260228_add_cover
Revises:
Create Date: 2026-02-28 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260228_add_cover"
down_revision = None  # TODO: Update this to your previous migration ID


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "llm_telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("images_generated", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cover_path", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.drop_column("cover_path")

    op.drop_table("llm_telemetry")
    # ### end Alembic commands ###
