"""Add request_type to escalation_requests

Revision ID: 27a510181d97
Revises: 52dbd8310811
Create Date: 2026-07-24 14:56:17.609589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a510181d97'
down_revision = '52dbd8310811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escalation_requests', schema='inventory') as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.String(length=20), server_default='correction', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escalation_requests', schema='inventory') as batch_op:
        batch_op.drop_column('request_type')
    # ### end Alembic commands ###
