"""add user profiles auth and rbac

Revision ID: 2973a4475ace
Revises: 20260228_add_cover
Create Date: 2026-03-07 20:28:22.947502

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#

import uuid
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2973a4475ace"
down_revision = "20260228_add_cover"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permissions_name"), ["name"], unique=True)

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("google_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("visibility", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_consents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("consent_type", sa.String(length=50), nullable=False),
        sa.Column("is_granted", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_consents_consent_type"), ["consent_type"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )

    # Seed default roles if they don't exist
    op.execute("INSERT INTO roles (name) VALUES ('user'), ('admin') ON CONFLICT DO NOTHING")

    # Seed a legacy system user to own orphan items during the transition to UUID-based ownership.
    # IMPORTANT: Existing items are assigned to this user by default to satisfy NOT NULL constraints. 
    # To recover these items and assign them to a real administrator, run `python scripts/init_auth.py`
    # after applying this migration.
    legacy_user_id = '00000000-0000-4000-a000-000000000000'
    op.execute(
        f"INSERT INTO users (id, email, display_name, is_active, created_at) "
        f"VALUES ('{legacy_user_id}', 'legacy@iqoqo.cc', 'Legacy System User', true, now()) "
        f"ON CONFLICT DO NOTHING"
    )

    # Safe migration for items owner_id to UUID
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("new_owner_id", sa.UUID(), nullable=True))

    # Assign all existing items to the legacy user
    op.execute(f"UPDATE items SET new_owner_id = '{legacy_user_id}'::uuid")

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column("new_owner_id", nullable=False)
        batch_op.drop_column("owner_id")
        batch_op.alter_column("new_owner_id", new_column_name="owner_id")
        batch_op.create_index(batch_op.f("ix_items_owner_id"), ["owner_id"], unique=False)
        batch_op.create_foreign_key(None, "users", ["owner_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_items_owner_id"))
        batch_op.alter_column("owner_id", existing_type=sa.UUID(), type_=sa.VARCHAR(length=100), nullable=True)

    op.drop_table("user_roles")
    with op.batch_alter_table("user_consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_consents_consent_type"))

    op.drop_table("user_consents")
    op.drop_table("role_permissions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))

    op.drop_table("roles")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_name"))

    op.drop_table("permissions")
    # ### end Alembic commands ###
