# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""Add Video and Board Game ontologies

Revision ID: 40408803b0ba
Revises: 1cc87cf008cd
Create Date: 2026-04-03 23:14:03.058398

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "40408803b0ba"
down_revision = "1cc87cf008cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def has_index(table_name, index_name, schema):
        indexes = inspector.get_indexes(table_name, schema=schema)
        return any(idx["name"] == index_name for idx in indexes)

    def has_constraint(table_name, constraint_name, schema):
        constraints = inspector.get_unique_constraints(table_name, schema=schema)
        return any(c["name"] == constraint_name for c in constraints)

    if not inspector.has_table("manifestation_contributions", schema="catalog"):
        op.create_table(
            "manifestation_contributions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("manifestation_id", sa.Integer(), nullable=False),
            sa.Column("contributor_id", sa.Integer(), nullable=False),
            sa.Column("role", sa.String(length=100), nullable=False),
            sa.Column("sequence", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["contributor_id"], ["catalog.contributors.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["manifestation_id"], ["catalog.manifestations.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            schema="catalog",
        )
        with op.batch_alter_table("manifestation_contributions", schema="catalog") as batch_op:
            batch_op.create_index("ix_manifestation_contributions_contributor_id", ["contributor_id"], unique=False)
            batch_op.create_index("ix_manifestation_contributions_manifestation_id", ["manifestation_id"], unique=False)

    if not inspector.has_table("container_aggregations", schema="catalog"):
        op.create_table(
            "container_aggregations",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("container_work_id", sa.Integer(), nullable=False),
            sa.Column("aggregated_type", sa.String(length=50), nullable=False),
            sa.Column("aggregated_work_id", sa.Integer(), nullable=True),
            sa.Column("aggregated_item_id", sa.Integer(), nullable=True),
            sa.Column("component_name", sa.String(length=255), nullable=False),
            sa.Column("quantity", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["aggregated_item_id"], ["inventory.items.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["aggregated_work_id"], ["catalog.works.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["container_work_id"], ["catalog.works.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            schema="catalog",
        )
        with op.batch_alter_table("container_aggregations", schema="catalog") as batch_op:
            batch_op.create_index("ix_container_aggregations_container_work_id", ["container_work_id"], unique=False)

    if inspector.has_table("permissions", schema="auth"):
        with op.batch_alter_table("permissions", schema="auth") as batch_op:
            if has_index("permissions", "ix_permissions_name", "auth"):
                batch_op.drop_index("ix_permissions_name")
            if not has_index("permissions", "ix_auth_permissions_name", "auth"):
                batch_op.create_index("ix_auth_permissions_name", ["name"], unique=True)

    if inspector.has_table("roles", schema="auth"):
        with op.batch_alter_table("roles", schema="auth") as batch_op:
            if has_index("roles", "ix_roles_name", "auth"):
                batch_op.drop_index("ix_roles_name")
            if not has_index("roles", "ix_auth_roles_name", "auth"):
                batch_op.create_index("ix_auth_roles_name", ["name"], unique=True)

    if inspector.has_table("token_blocklist", schema="auth"):
        with op.batch_alter_table("token_blocklist", schema="auth") as batch_op:
            batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
            if has_index("token_blocklist", "ix_token_blocklist_jti", "auth"):
                batch_op.drop_index("ix_token_blocklist_jti")
            if not has_index("token_blocklist", "ix_auth_token_blocklist_jti", "auth"):
                batch_op.create_index("ix_auth_token_blocklist_jti", ["jti"], unique=False)

    if inspector.has_table("user_consents", schema="auth"):
        with op.batch_alter_table("user_consents", schema="auth") as batch_op:
            if has_index("user_consents", "ix_user_consents_consent_type", "auth"):
                batch_op.drop_index("ix_user_consents_consent_type")
            if not has_index("user_consents", "ix_auth_user_consents_consent_type", "auth"):
                batch_op.create_index("ix_auth_user_consents_consent_type", ["consent_type"], unique=False)

    if inspector.has_table("users", schema="auth"):
        with op.batch_alter_table("users", schema="auth") as batch_op:
            if has_index("users", "ix_users_email", "auth"):
                batch_op.drop_index("ix_users_email")
            if not has_index("users", "ix_auth_users_email", "auth"):
                batch_op.create_index("ix_auth_users_email", ["email"], unique=True)

    if inspector.has_table("contributors", schema="catalog"):
        with op.batch_alter_table("contributors", schema="catalog") as batch_op:
            batch_op.alter_column("type", existing_type=sa.VARCHAR(length=20), server_default=None, existing_nullable=False)
            if has_index("contributors", "ix_contributors_name", "catalog"):
                batch_op.drop_index("ix_contributors_name")
            if not has_index("contributors", "ix_catalog_contributors_name", "catalog"):
                batch_op.create_index("ix_catalog_contributors_name", ["name"], unique=False)
            if not has_constraint("contributors", "uq_contributor_name_type", "catalog"):
                batch_op.create_unique_constraint("uq_contributor_name_type", ["name", "type"])

    if inspector.has_table("expression_contributions", schema="catalog"):
        with op.batch_alter_table("expression_contributions", schema="catalog") as batch_op:
            batch_op.alter_column("sequence", existing_type=sa.INTEGER(), server_default=None, existing_nullable=True)

    if inspector.has_table("manifestations", schema="catalog"):
        with op.batch_alter_table("manifestations", schema="catalog") as batch_op:
            if has_index("manifestations", "ix_manifestations_ean", "catalog"):
                batch_op.drop_index("ix_manifestations_ean")
            if has_index("manifestations", "ix_manifestations_isbn13", "catalog"):
                batch_op.drop_index("ix_manifestations_isbn13")
            if has_index("manifestations", "ix_manifestations_upc", "catalog"):
                batch_op.drop_index("ix_manifestations_upc")
            if not has_index("manifestations", "ix_catalog_manifestations_ean", "catalog"):
                batch_op.create_index("ix_catalog_manifestations_ean", ["ean"], unique=False)
            if not has_index("manifestations", "ix_catalog_manifestations_isbn13", "catalog"):
                batch_op.create_index("ix_catalog_manifestations_isbn13", ["isbn13"], unique=True)
            if not has_index("manifestations", "ix_catalog_manifestations_upc", "catalog"):
                batch_op.create_index("ix_catalog_manifestations_upc", ["upc"], unique=False)

    if inspector.has_table("work_contributions", schema="catalog"):
        with op.batch_alter_table("work_contributions", schema="catalog") as batch_op:
            batch_op.alter_column("sequence", existing_type=sa.INTEGER(), server_default=None, existing_nullable=True)

    if inspector.has_table("work_parts", schema="catalog"):
        with op.batch_alter_table("work_parts", schema="catalog") as batch_op:
            batch_op.alter_column("sequence", existing_type=sa.INTEGER(), server_default=None, existing_nullable=True)

    if inspector.has_table("items", schema="inventory"):
        with op.batch_alter_table("items", schema="inventory") as batch_op:
            if has_index("items", "ix_items_owner_id", "inventory"):
                batch_op.drop_index("ix_items_owner_id")
            if not has_index("items", "ix_inventory_items_owner_id", "inventory"):
                batch_op.create_index("ix_inventory_items_owner_id", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_items_owner_id"))
        batch_op.create_index(batch_op.f("ix_items_owner_id"), ["owner_id"], unique=False)

    with op.batch_alter_table("work_parts", schema="catalog") as batch_op:
        batch_op.alter_column("sequence", existing_type=sa.INTEGER(), server_default=sa.text("0"), existing_nullable=True)

    with op.batch_alter_table("work_contributions", schema="catalog") as batch_op:
        batch_op.alter_column("sequence", existing_type=sa.INTEGER(), server_default=sa.text("0"), existing_nullable=True)

    with op.batch_alter_table("manifestations", schema="catalog") as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_manifestations_upc"))
        batch_op.drop_index(batch_op.f("ix_catalog_manifestations_isbn13"))
        batch_op.drop_index(batch_op.f("ix_catalog_manifestations_ean"))
        batch_op.create_index(batch_op.f("ix_manifestations_upc"), ["upc"], unique=False)
        batch_op.create_index(batch_op.f("ix_manifestations_isbn13"), ["isbn13"], unique=True)
        batch_op.create_index(batch_op.f("ix_manifestations_ean"), ["ean"], unique=False)

    with op.batch_alter_table("expression_contributions", schema="catalog") as batch_op:
        batch_op.alter_column("sequence", existing_type=sa.INTEGER(), server_default=sa.text("0"), existing_nullable=True)

    with op.batch_alter_table("contributors", schema="catalog") as batch_op:
        batch_op.drop_constraint("uq_contributor_name_type", type_="unique")
        batch_op.drop_index(batch_op.f("ix_catalog_contributors_name"))
        batch_op.create_index(batch_op.f("ix_contributors_name"), ["name"], unique=False)
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=20), server_default=sa.text("'person'::character varying"), existing_nullable=False
        )

    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_users_email"))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    with op.batch_alter_table("user_consents", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_user_consents_consent_type"))
        batch_op.create_index(batch_op.f("ix_user_consents_consent_type"), ["consent_type"], unique=False)

    with op.batch_alter_table("token_blocklist", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_token_blocklist_jti"))
        batch_op.create_index(batch_op.f("ix_token_blocklist_jti"), ["jti"], unique=False)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("roles", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_roles_name"))
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)

    with op.batch_alter_table("permissions", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_permissions_name"))
        batch_op.create_index(batch_op.f("ix_permissions_name"), ["name"], unique=True)

    with op.batch_alter_table("container_aggregations", schema="catalog") as batch_op:
        batch_op.drop_index("ix_container_aggregations_container_work_id")

    op.drop_table("container_aggregations", schema="catalog")
    with op.batch_alter_table("manifestation_contributions", schema="catalog") as batch_op:
        batch_op.drop_index("ix_manifestation_contributions_manifestation_id")
        batch_op.drop_index("ix_manifestation_contributions_contributor_id")

    op.drop_table("manifestation_contributions", schema="catalog")
    # ### end Alembic commands ###
