"""Add user_id and total_duration_seconds to llm_telemetry; composite unique constraint

Revision ID: 46385ad9cce1
Revises: d7f3894e9f8b
Create Date: 2026-03-19 22:57:44.091381

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "46385ad9cce1"
down_revision = "d7f3894e9f8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=100), nullable=True, server_default="system"))
        batch_op.add_column(sa.Column("total_duration_seconds", sa.Float(), nullable=True))

    op.execute("UPDATE llm_telemetry SET user_id = 'system' WHERE user_id IS NULL")

    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.String(length=100),
            nullable=False,
            existing_nullable=True,
            server_default=None,
            existing_server_default="system",
        )
        batch_op.drop_constraint(batch_op.f("llm_telemetry_provider_key"), type_="unique")
        batch_op.create_unique_constraint("uq_provider_user", ["provider", "user_id"])

    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manifestations_fts"), postgresql_using="gin")
        batch_op.drop_column("fts_simple")

    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_works_fts"), postgresql_using="gin")
        batch_op.drop_column("fts_simple")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fts_simple",
                postgresql.TSVECTOR(),
                sa.Computed(
                    "to_tsvector('simple'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE((meta ->> 'authors'::text), ''::text)))",
                    persisted=True,
                ),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_index(batch_op.f("ix_works_fts"), ["fts_simple"], unique=False, postgresql_using="gin")

    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fts_simple",
                postgresql.TSVECTOR(),
                sa.Computed(
                    "to_tsvector('simple'::regconfig, (((((COALESCE(isbn13, ''::character varying))::text || ' '::text) || COALESCE((meta ->> 'publisher'::text), ''::text)) || ' '::text) || COALESCE((meta ->> 'alt_title'::text), ''::text)))",
                    persisted=True,
                ),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_index(batch_op.f("ix_manifestations_fts"), ["fts_simple"], unique=False, postgresql_using="gin")

    with op.batch_alter_table("llm_telemetry", schema=None) as batch_op:
        batch_op.drop_constraint("uq_provider_user", type_="unique")
        batch_op.create_unique_constraint(batch_op.f("llm_telemetry_provider_key"), ["provider"], postgresql_nulls_not_distinct=False)
        batch_op.drop_column("total_duration_seconds")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
