"""Add UserCollection and Tag taxonomy models

Revision ID: 49dedc457aa3
Revises: 070_social_sharing
Create Date: 2026-05-18 23:05:00.280678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49dedc457aa3'
down_revision = '070_social_sharing'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    with op.batch_alter_table('tags', schema='catalog') as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_tags_name'), ['name'], unique=True)

    op.create_table('user_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory.user_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    with op.batch_alter_table('user_collections', schema='inventory') as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_user_collections_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_user_collections_parent_id'), ['parent_id'], unique=False)

    op.create_table('item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['catalog.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    with op.batch_alter_table('item_tags', schema='inventory') as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_item_tags_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_item_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('user_collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['inventory.user_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    with op.batch_alter_table('user_collection_items', schema='inventory') as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_user_collection_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_user_collection_items_item_id'), ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection_items', schema='inventory') as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_user_collection_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_user_collection_items_collection_id'))

    op.drop_table('user_collection_items', schema='inventory')
    with op.batch_alter_table('item_tags', schema='inventory') as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_item_tags_item_id'))

    op.drop_table('item_tags', schema='inventory')
    with op.batch_alter_table('user_collections', schema='inventory') as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_user_collections_parent_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_user_collections_owner_id'))

    op.drop_table('user_collections', schema='inventory')
    with op.batch_alter_table('tags', schema='catalog') as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_tags_name'))

    op.drop_table('tags', schema='catalog')
    # ### end Alembic commands ###
