# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
"""add lending tables

Revision ID: 52b02a37b16b
Revises: 23db780ad6d1
Create Date: 2026-06-04 21:25:31.775845

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "52b02a37b16b"
down_revision = "23db780ad6d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loan_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["inventory.items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    with op.batch_alter_table("loan_requests", schema="inventory") as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_loan_requests_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_loan_requests_requester_id"), ["requester_id"], unique=False)

    op.drop_table("image_scans", schema="inventory")
    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_public_visibility"))
        batch_op.drop_constraint(batch_op.f("uq_users_public_username"), type_="unique")
        batch_op.create_index(batch_op.f("ix_auth_users_public_username"), ["public_username"], unique=True)

    with op.batch_alter_table("expressions", schema="catalog") as batch_op:
        batch_op.drop_constraint(batch_op.f("expressions_work_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "works", ["work_id"], ["id"], referent_schema="catalog", ondelete="CASCADE")

    with op.batch_alter_table("image_scans", schema="catalog") as batch_op:
        batch_op.alter_column("file_path", existing_type=sa.VARCHAR(length=500), type_=sa.String(length=255), existing_nullable=False)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=None, existing_nullable=True)

    with op.batch_alter_table("instance_settings", schema="catalog") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False, autoincrement=True)
        batch_op.drop_index(batch_op.f("ix_instance_settings_key"))
        batch_op.create_index(batch_op.f("ix_catalog_instance_settings_key"), ["key"], unique=True)

    with op.batch_alter_table("manifestations", schema="catalog") as batch_op:
        batch_op.drop_constraint(batch_op.f("manifestations_expression_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "expressions", ["expression_id"], ["id"], referent_schema="catalog", ondelete="CASCADE")

    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.alter_column("is_hidden", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
        batch_op.drop_index(batch_op.f("ix_items_owner_hidden"))
        batch_op.drop_constraint(batch_op.f("items_manifestation_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(None, "manifestations", ["manifestation_id"], ["id"], referent_schema="catalog", ondelete="CASCADE")
        batch_op.drop_column("progress_status")

    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False, autoincrement=True)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=20), nullable=False)

    with op.batch_alter_table("scan_telemetry", schema="inventory") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=None, nullable=False)

    with op.batch_alter_table("shared_collections", schema="inventory") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=None, existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_collections", schema="inventory") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=sa.text("now()"), existing_nullable=True)

    with op.batch_alter_table("scan_telemetry", schema="inventory") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=sa.text("now()"), nullable=True)

    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=20), nullable=True)
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.add_column(
            sa.Column(
                "progress_status",
                sa.VARCHAR(length=50),
                server_default=sa.text("'unstarted'::character varying"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("items_manifestation_id_fkey"), "manifestations", ["manifestation_id"], ["id"], referent_schema="catalog"
        )
        batch_op.create_index(batch_op.f("ix_items_owner_hidden"), ["owner_id", "is_hidden"], unique=False)
        batch_op.alter_column("is_hidden", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)

    with op.batch_alter_table("manifestations", schema="catalog") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("manifestations_expression_id_fkey"), "expressions", ["expression_id"], ["id"], referent_schema="catalog"
        )

    with op.batch_alter_table("instance_settings", schema="catalog") as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_instance_settings_key"))
        batch_op.create_index(batch_op.f("ix_instance_settings_key"), ["key"], unique=True)
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("image_scans", schema="catalog") as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), server_default=sa.text("now()"), existing_nullable=True)
        batch_op.alter_column("file_path", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=500), existing_nullable=False)

    with op.batch_alter_table("expressions", schema="catalog") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(batch_op.f("expressions_work_id_fkey"), "works", ["work_id"], ["id"], referent_schema="catalog")

    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_users_public_username"))
        batch_op.create_unique_constraint(batch_op.f("uq_users_public_username"), ["public_username"], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f("ix_users_public_visibility"), ["public_username", "visibility"], unique=False)

    op.create_table(
        "image_scans",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("scan_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("image_path", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["inventory.items.id"], name=op.f("fk_item"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("image_scans_pkey")),
        schema="inventory",
    )
    with op.batch_alter_table("loan_requests", schema="inventory") as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_loan_requests_requester_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_loan_requests_item_id"))

    op.drop_table("loan_requests", schema="inventory")
    # ### end Alembic commands ###
