# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""add_item_status_logs_and_image_scans

Revision ID: 977a397c8f7c
Revises: consolidate_schemas
Create Date: 2026-04-15 13:56:09.137571

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "977a397c8f7c"
down_revision = "consolidate_schemas"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def has_index(table_name, index_name, schema=None):
        indexes = inspector.get_indexes(table_name, schema=schema)
        return any(idx["name"] == index_name for idx in indexes)

    if not inspector.has_table("image_scans", schema="catalog"):
        op.create_table(
            "image_scans",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("manifestation_id", sa.Integer(), nullable=False),
            sa.Column("file_path", sa.String(length=255), nullable=False),
            sa.Column("scan_type", sa.String(length=50), nullable=True),
            sa.Column("source", sa.String(length=100), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(["manifestation_id"], ["catalog.manifestations.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            schema="catalog",
        )

    if not inspector.has_table("item_status_logs", schema="inventory"):
        op.create_table(
            "item_status_logs",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("item_id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.UUID(), nullable=False),
            sa.Column("old_status", sa.String(length=50), nullable=True),
            sa.Column("new_status", sa.String(length=50), nullable=False),
            sa.Column("changed_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(["item_id"], ["inventory.items.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            schema="inventory",
        )

    if inspector.has_table("instance_settings", schema="catalog"):
        with op.batch_alter_table("instance_settings", schema="catalog") as batch_op:
            if has_index("instance_settings", "instance_settings_key_idx", "catalog"):
                batch_op.drop_index("instance_settings_key_idx")
            if not has_index("instance_settings", "ix_catalog_instance_settings_key", "catalog"):
                batch_op.create_index(batch_op.f("ix_catalog_instance_settings_key"), ["key"], unique=True)

    if inspector.has_table("llm_telemetry", schema="inventory"):
        with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
            if has_index("llm_telemetry", "llm_telemetry_provider_user_id_operation_type_created_at_idx", "inventory"):
                batch_op.drop_index("llm_telemetry_provider_user_id_operation_type_created_at_idx")
            if not has_index("llm_telemetry", "ix_llm_telemetry_provider_user_op_time", "inventory"):
                batch_op.create_index(
                    "ix_llm_telemetry_provider_user_op_time", ["provider", "user_id", "operation_type", "created_at"], unique=False
                )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.drop_index("ix_llm_telemetry_provider_user_op_time")
        batch_op.create_index(
            batch_op.f("llm_telemetry_provider_user_id_operation_type_created_at_idx"),
            ["provider", "user_id", "operation_type", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("instance_settings", schema="catalog") as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_instance_settings_key"))
        batch_op.create_index(batch_op.f("instance_settings_key_idx"), ["key"], unique=True)

    op.drop_table("item_status_logs", schema="inventory")
    op.drop_table("image_scans", schema="catalog")
    # ### end Alembic commands ###
