# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

"""fix_llm_telemetry_id_identity

Revision ID: 9ed9e764c2b0
Revises: c1701b7fea50
Create Date: 2026-04-15 22:41:04.389967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed9e764c2b0'
down_revision = 'c1701b7fea50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually ensure identity on the 'id' column of inventory.llm_telemetry
    # This is needed because the schema move potentially broke the sequence link.
    
    # 1. Clear any existing (potentially broken) defaults
    op.execute("ALTER TABLE inventory.llm_telemetry ALTER COLUMN id DROP DEFAULT")
    
    # 2. Add identity (Postgres 10+)
    # We use 'IF NOT EXISTS' equivalent via a check if needed, but here simple ADD works if we cleared defaults.
    # Note: If it already had an identity, this might fail, so we wrap it.
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_attribute 
                WHERE attrelid = 'inventory.llm_telemetry'::regclass 
                AND attname = 'id' 
                AND attidentity IN ('a', 'd')
            ) THEN
                ALTER TABLE inventory.llm_telemetry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
    """)
    
    # 3. Restart sequence at max(id) + 1 to avoid collisions
    op.execute("SELECT setval(pg_get_serial_sequence('inventory.llm_telemetry', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM inventory.llm_telemetry")

    with op.batch_alter_table('llm_telemetry', schema='inventory') as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_telemetry', schema='inventory') as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'success'::character varying"),
               existing_nullable=False)

    # Best-effort reversal of identity column back to traditional sequence.
    # Note: This is not perfectly reversible as the identity vs serial/default
    # behavior differs in internal Postgres catalog links.
    try:
        op.execute("ALTER TABLE inventory.llm_telemetry ALTER COLUMN id DROP IDENTITY IF EXISTS")
        # Attempt to link back to the sequence - assumes it still exists or was named standardly
        op.execute("ALTER TABLE inventory.llm_telemetry ALTER COLUMN id SET DEFAULT nextval('inventory.llm_telemetry_id_seq')")
    except Exception:  # pylint: disable=broad-except
        # If downgrade fails (e.g. sequence was dropped/renamed by PG identity machinery), 
        # we log and continue as the table structure is technically still viable.
        print("Warning: Failed to fully restore llm_telemetry.id default sequence. Manual intervention may be needed.")

    # ### end Alembic commands ###
