# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

"""add lent_to columns to items

Revision ID: 9fde62a10d5e
Revises: 9f5598cf6467
Create Date: 2026-04-28 22:34:12.850388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fde62a10d5e"
down_revision = "9f5598cf6467"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.add_column(sa.Column("lent_to_user_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("lent_to_name", sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f("ix_inventory_items_lent_to_user_id"), ["lent_to_user_id"], unique=False)
        batch_op.create_foreign_key(None, "users", ["lent_to_user_id"], ["id"], referent_schema="auth", ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_inventory_items_lent_to_user_id"))
        batch_op.drop_column("lent_to_name")
        batch_op.drop_column("lent_to_user_id")
    # ### end Alembic commands ###
