# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

"""add lent_to columns to items

Revision ID: 9fde62a10d5e
Revises: 9f5598cf6467
Create Date: 2026-04-28 22:34:12.850388

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fde62a10d5e"
down_revision = "9f5598cf6467"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def has_column(table_name, column_name, schema=None):
        columns = inspector.get_columns(table_name, schema=schema)
        return any(c["name"] == column_name for c in columns)

    def has_index(table_name, index_name, schema=None):
        indexes = inspector.get_indexes(table_name, schema=schema)
        return any(idx["name"] == index_name for idx in indexes)

    if inspector.has_table("items", schema="inventory"):
        with op.batch_alter_table("items", schema="inventory") as batch_op:
            if not has_column("items", "lent_to_user_id", "inventory"):
                batch_op.add_column(sa.Column("lent_to_user_id", sa.UUID(), nullable=True))
            if not has_column("items", "lent_to_name", "inventory"):
                batch_op.add_column(sa.Column("lent_to_name", sa.String(length=255), nullable=True))
            if not has_index("items", "ix_inventory_items_lent_to_user_id", "inventory"):
                batch_op.create_index(batch_op.f("ix_inventory_items_lent_to_user_id"), ["lent_to_user_id"], unique=False)

            fks = inspector.get_foreign_keys("items", schema="inventory")
            has_fk = any(
                fk["referred_table"] == "users" and fk["referred_schema"] == "auth" and "lent_to_user_id" in fk["constrained_columns"]
                for fk in fks
            )
            if not has_fk:
                batch_op.create_foreign_key(None, "users", ["lent_to_user_id"], ["id"], referent_schema="auth", ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_inventory_items_lent_to_user_id"))
        batch_op.drop_column("lent_to_name")
        batch_op.drop_column("lent_to_user_id")
    # ### end Alembic commands ###
