"""Preserve escalation_requests history on entity deletion

Revision ID: b7ad7843fb4a
Revises: 27a510181d97
Create Date: 2026-07-24 15:13:51.695001

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ad7843fb4a'
down_revision = '27a510181d97'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("escalation_requests", schema="inventory")]

    with op.batch_alter_table("escalation_requests", schema="inventory") as batch_op:
        if "target_type" not in columns:
            batch_op.add_column(sa.Column("target_type", sa.String(length=20), nullable=True))
        batch_op.drop_constraint('chk_escalation_target_exactly_one', type_='check')
        batch_op.create_check_constraint(
            'chk_escalation_target_exactly_one',
            '(case when work_id is not null then 1 else 0 end + '
            'case when expression_id is not null then 1 else 0 end + '
            'case when manifestation_id is not null then 1 else 0 end + '
            'case when item_id is not null then 1 else 0 end) <= 1'
        )
        batch_op.drop_constraint('escalation_requests_manifestation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('escalation_requests_work_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('escalation_requests_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('escalation_requests_expression_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('escalation_requests_work_id_fkey', 'works', ['work_id'], ['id'], referent_schema='catalog', ondelete='SET NULL')
        batch_op.create_foreign_key('escalation_requests_manifestation_id_fkey', 'manifestations', ['manifestation_id'], ['id'], referent_schema='catalog', ondelete='SET NULL')
        batch_op.create_foreign_key('escalation_requests_expression_id_fkey', 'expressions', ['expression_id'], ['id'], referent_schema='catalog', ondelete='SET NULL')
        batch_op.create_foreign_key('escalation_requests_item_id_fkey', 'items', ['item_id'], ['id'], referent_schema='inventory', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escalation_requests', schema='inventory') as batch_op:
        batch_op.drop_constraint('escalation_requests_manifestation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('escalation_requests_work_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('escalation_requests_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('escalation_requests_expression_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('escalation_requests_expression_id_fkey', 'expressions', ['expression_id'], ['id'], referent_schema='catalog', ondelete='CASCADE')
        batch_op.create_foreign_key('escalation_requests_item_id_fkey', 'items', ['item_id'], ['id'], referent_schema='inventory', ondelete='CASCADE')
        batch_op.create_foreign_key('escalation_requests_work_id_fkey', 'works', ['work_id'], ['id'], referent_schema='catalog', ondelete='CASCADE')
        batch_op.create_foreign_key('escalation_requests_manifestation_id_fkey', 'manifestations', ['manifestation_id'], ['id'], referent_schema='catalog', ondelete='CASCADE')
        batch_op.drop_constraint('chk_escalation_target_exactly_one', type_='check')
        batch_op.create_check_constraint(
            'chk_escalation_target_exactly_one',
            '(case when work_id is not null then 1 else 0 end + '
            'case when expression_id is not null then 1 else 0 end + '
            'case when manifestation_id is not null then 1 else 0 end + '
            'case when item_id is not null then 1 else 0 end) = 1'
        )
        batch_op.drop_column('target_type')
    # ### end Alembic commands ###
