# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

"""add_llm_status_and_scan_telemetry

Revision ID: c1701b7fea50
Revises: 977a397c8f7c
Create Date: 2026-04-15 22:04:51.815891

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c1701b7fea50"
down_revision = "977a397c8f7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(length=50), nullable=False),
        sa.Column("format_hint", sa.String(length=50), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("manifestation_id", sa.Integer(), nullable=True),
        sa.Column("raw_request_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manifestation_id"],
            ["catalog.manifestations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    with op.batch_alter_table("scan_telemetry", schema="inventory") as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_scan_telemetry_barcode"), ["barcode"], unique=False)

    # Note: Removing server-side default for collection_status.
    # This aligns the database with the modern ORM model which manages
    # defaults at the application/SQLAlchemy level.
    # Guard: only run if the column exists with a server_default. Databases built
    # fresh via the schema-separation migration path create the column without a
    # server_default, so this ALTER would fail with "column does not exist" on
    # PostgreSQL when the column was never given a default to begin with.
    bind = op.get_bind()
    from sqlalchemy import inspect as sa_inspect  # noqa: PLC0415

    inspector = sa_inspect(bind)
    cols = {c["name"]: c for c in inspector.get_columns("items", schema="inventory")}
    if "collection_status" in cols and cols["collection_status"].get("default") is not None:
        with op.batch_alter_table("items", schema="inventory") as batch_op:
            batch_op.alter_column("collection_status", existing_type=sa.VARCHAR(length=50), server_default=None, existing_nullable=True)

    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False, server_default="success"))
        batch_op.add_column(sa.Column("error_message", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_telemetry", schema="inventory") as batch_op:
        batch_op.drop_column("error_message")
        batch_op.drop_column("status")

    with op.batch_alter_table("items", schema="inventory") as batch_op:
        batch_op.alter_column(
            "collection_status",
            existing_type=sa.VARCHAR(length=50),
            server_default=sa.text("'available'::character varying"),
            existing_nullable=True,
        )

    with op.batch_alter_table("scan_telemetry", schema="inventory") as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_scan_telemetry_barcode"))

    op.drop_table("scan_telemetry", schema="inventory")
    # ### end Alembic commands ###
