"""fix instance_settings id identity

Revision ID: ca691f79cb37
Revises: 9fde62a10d5e
Create Date: 2026-05-12 19:35:53.536816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca691f79cb37'
down_revision = '9fde62a10d5e'
branch_labels = None
depends_on = None


def upgrade():
    """Ensure identity on the 'id' column of catalog.instance_settings."""
    # 1. Clear any existing (potentially broken) defaults
    op.execute("ALTER TABLE catalog.instance_settings ALTER COLUMN id DROP DEFAULT")
    
    # 2. Add identity (Postgres 10+)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_attribute 
                WHERE attrelid = 'catalog.instance_settings'::regclass 
                AND attname = 'id' 
                AND attidentity IN ('a', 'd')
            ) THEN
                ALTER TABLE catalog.instance_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
    """)
    
    # 3. Restart sequence at max(id) + 1 to avoid collisions
    op.execute("SELECT setval(pg_get_serial_sequence('catalog.instance_settings', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM catalog.instance_settings")


def downgrade():
    """Rollback identity column back to traditional sequence."""
    try:
        op.execute("ALTER TABLE catalog.instance_settings ALTER COLUMN id DROP IDENTITY IF EXISTS")
        # Attempt to link back to the sequence - assumes it still exists or was named standardly
        op.execute("ALTER TABLE catalog.instance_settings ALTER COLUMN id SET DEFAULT nextval('catalog.instance_settings_id_seq')")
    except Exception:  # pylint: disable=broad-except
        print("Warning: Failed to fully restore instance_settings.id default sequence.")
