"""refactor cover_path to cover_url

Revision ID: d7f3894e9f8b
Revises: 9549d8c37cbc
Create Date: 2026-03-15 22:48:12.821548

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7f3894e9f8b"
down_revision = "9549d8c37cbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.alter_column(column_name="cover_path", new_column_name="cover_url")
        # batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.alter_column(column_name="cover_url", new_column_name="cover_path")

    # ### end Alembic commands ###
