"""Increase title and publisher field lengths

Revision ID: f53e05847e86
Revises: 0a9010ed74e4
Create Date: 2026-01-30 00:26:59.780877

"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f53e05847e86"
down_revision = "0a9010ed74e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expressions", schema=None) as batch_op:
        batch_op.alter_column("meta", existing_type=postgresql.JSONB(astext_type=sa.Text()), type_=sa.JSON(), existing_nullable=True)

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column("meta", existing_type=postgresql.JSONB(astext_type=sa.Text()), type_=sa.JSON(), existing_nullable=True)

    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.alter_column("publisher", existing_type=sa.VARCHAR(length=255), type_=sa.String(length=500), existing_nullable=True)
        batch_op.alter_column("meta", existing_type=postgresql.JSONB(astext_type=sa.Text()), type_=sa.JSON(), existing_nullable=True)

    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.alter_column("title", existing_type=sa.VARCHAR(length=255), type_=sa.String(length=1000), existing_nullable=False)
        batch_op.alter_column("meta", existing_type=postgresql.JSONB(astext_type=sa.Text()), type_=sa.JSON(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.alter_column("meta", existing_type=sa.JSON(), type_=postgresql.JSONB(astext_type=sa.Text()), existing_nullable=True)
        batch_op.alter_column("title", existing_type=sa.String(length=1000), type_=sa.VARCHAR(length=255), existing_nullable=False)

    with op.batch_alter_table("manifestations", schema=None) as batch_op:
        batch_op.alter_column("meta", existing_type=sa.JSON(), type_=postgresql.JSONB(astext_type=sa.Text()), existing_nullable=True)
        batch_op.alter_column("publisher", existing_type=sa.String(length=500), type_=sa.VARCHAR(length=255), existing_nullable=True)

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column("meta", existing_type=sa.JSON(), type_=postgresql.JSONB(astext_type=sa.Text()), existing_nullable=True)

    with op.batch_alter_table("expressions", schema=None) as batch_op:
        batch_op.alter_column("meta", existing_type=sa.JSON(), type_=postgresql.JSONB(astext_type=sa.Text()), existing_nullable=True)

    # ### end Alembic commands ###
