# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""Consolidated baseline schema migration for v0.7.17.

Revision ID: v0_7_17_baseline
Revises: None
Create Date: 2026-09-12
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.search_types import SearchVector

# revision identifiers, used by Alembic.
revision = "v0_7_17_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"
    inspector = sa.inspect(bind)

    s_auth = "auth" if is_pg else None
    s_cat = "catalog" if is_pg else None
    s_inv = "inventory" if is_pg else None
    s_soc = "social" if is_pg else None

    s_auth_pfx = f"{s_auth}." if s_auth else ""
    s_cat_pfx = f"{s_cat}." if s_cat else ""
    s_inv_pfx = f"{s_inv}." if s_inv else ""
    s_soc_pfx = f"{s_soc}." if s_soc else ""

    if is_pg:
        for schema in ("auth", "catalog", "inventory", "social"):
            op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # If database tables already exist (e.g. existing production database upgraded from f65648a6aaf4),
    # safely perform schema migration for settings and skip duplicate table creations.
    existing_works = (
        inspector.has_table("works", schema=s_cat)
        if is_pg
        else inspector.has_table("works")
    )
    if existing_works:
        return

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=s_auth
    )
    op.create_index(op.f('ix_auth_permissions_name'), 'permissions', ['name'], unique=True, schema=s_auth)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=s_auth
    )
    op.create_index(op.f('ix_auth_roles_name'), 'roles', ['name'], unique=True, schema=s_auth)
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=s_auth
    )
    op.create_index(op.f('ix_auth_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False, schema=s_auth)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('public_username', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    schema=s_auth
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema=s_auth)
    op.create_index(op.f('ix_auth_users_public_username'), 'users', ['public_username'], unique=True, schema=s_auth)
    op.create_table('boardgame_mechanics',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bgg_id', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_boardgame_mechanics_bgg_id'), 'boardgame_mechanics', ['bgg_id'], unique=False, schema=s_cat)
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_contributor_name_type'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_contributors_name'), 'contributors', ['name'], unique=False, schema=s_cat)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_tags_name'), 'tags', ['name'], unique=True, schema=s_cat)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('sort_title', sa.String(length=1000), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fts_simple', SearchVector(), sa.Computed("to_tsvector('simple'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE((meta ->> 'authors'::text), ''::text)))", persisted=True), nullable=True),
    sa.Column('search_vector', SearchVector(), server_default=sa.FetchedValue(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_works_sort_title'), 'works', ['sort_title'], unique=False, schema=s_cat)
    op.create_index('ix_works_fts', 'works', ['fts_simple'], unique=False, schema=s_cat, postgresql_using='gin')
    op.create_index('ix_works_search_vector', 'works', ['search_vector'], unique=False, schema=s_cat, postgresql_using='gin')
    op.create_table('instance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_instance_settings_key'), 'instance_settings', ['key'], unique=True, schema=s_cat)
    op.create_table('llm_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('images_generated', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index('ix_llm_telemetry_provider_user_op_time', 'llm_telemetry', ['provider', 'user_id', 'operation_type', 'created_at'], unique=False, schema=s_inv)
    op.create_table('metadata_refetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('iqoqo_version', sa.String(length=50), nullable=False),
    sa.Column('found_fields', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'strategy', name='uq_metadata_refetch_log'),
    schema=s_inv
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], [f"{s_auth_pfx}permissions.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], [f"{s_auth_pfx}roles.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema=s_auth
    )
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_auth
    )
    op.create_index(op.f('ix_auth_user_consents_consent_type'), 'user_consents', ['consent_type'], unique=False, schema=s_auth)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], [f"{s_auth_pfx}roles.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema=s_auth
    )
    op.create_table('expressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_expressions_kind'), 'expressions', ['kind'], unique=False, schema=s_cat)
    op.create_table('reading_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_table('work_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], [f"{s_cat_pfx}contributors.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index('ix_work_contributions_contributor_id', 'work_contributions', ['contributor_id'], unique=False, schema=s_cat)
    op.create_index('ix_work_contributions_work_id', 'work_contributions', ['work_id'], unique=False, schema=s_cat)
    op.create_table('work_expansion_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_work_id', sa.Integer(), nullable=False),
    sa.Column('expansion_work_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expansion_work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expansion_work_id'),
    schema=s_cat
    )
    op.create_index('ix_work_expansion_links_base_work_id', 'work_expansion_links', ['base_work_id'], unique=False, schema=s_cat)
    op.create_index('ix_work_expansion_links_expansion_work_id', 'work_expansion_links', ['expansion_work_id'], unique=False, schema=s_cat)
    op.create_table('work_parts',
    sa.Column('container_work_id', sa.Integer(), nullable=False),
    sa.Column('part_work_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('container_work_id', 'part_work_id'),
    schema=s_cat
    )
    op.create_index('ix_work_parts_container_work_id', 'work_parts', ['container_work_id'], unique=False, schema=s_cat)
    op.create_index('ix_work_parts_part_work_id', 'work_parts', ['part_work_id'], unique=False, schema=s_cat)
    op.create_table('entity_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=100), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], [f"{s_auth_pfx}users.id"], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index('ix_entity_audit_logs_entity', 'entity_audit_logs', ['entity_type', 'entity_id'], unique=False, schema=s_inv)
    op.create_index('ix_entity_audit_logs_logged_at', 'entity_audit_logs', ['logged_at'], unique=False, schema=s_inv)
    op.create_table('shared_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    schema=s_inv
    )
    op.create_table('user_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], [f"{s_inv_pfx}user_collections.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_user_collections_owner_id'), 'user_collections', ['owner_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_user_collections_parent_id'), 'user_collections', ['parent_id'], unique=False, schema=s_inv)
    op.create_table('user_work_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_id', name='uq_user_work_intent'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_user_work_intents_user_id'), 'user_work_intents', ['user_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_user_work_intents_work_id'), 'user_work_intents', ['work_id'], unique=False, schema=s_inv)
    op.create_table('feedback_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("feedback_type IN ('feature_request', 'bug')", name='chk_feedback_item_type'),
    sa.CheckConstraint("status IN ('new', 'accepted', 'in_progress', 'in_validation', 'closed')", name='chk_feedback_item_status'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_soc
    )
    op.create_index(op.f('ix_social_feedback_items_status'), 'feedback_items', ['status'], unique=False, schema=s_soc)
    op.create_index(op.f('ix_social_feedback_items_user_id'), 'feedback_items', ['user_id'], unique=False, schema=s_soc)
    op.create_table('expression_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], [f"{s_cat_pfx}contributors.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expression_id'], [f"{s_cat_pfx}expressions.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index('ix_expression_contributions_contributor_id', 'expression_contributions', ['contributor_id'], unique=False, schema=s_cat)
    op.create_index('ix_expression_contributions_expression_id', 'expression_contributions', ['expression_id'], unique=False, schema=s_cat)
    op.create_table('manifestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression_id', sa.Integer(), nullable=False),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('upc', sa.String(length=12), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('catalog_number', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fts_simple', SearchVector(), sa.Computed("to_tsvector('simple'::regconfig, (((((COALESCE(isbn13, ''::character varying))::text || ' '::text) || COALESCE((meta ->> 'publisher'::text), ''::text)) || ' '::text) || COALESCE((meta ->> 'alt_title'::text), ''::text)))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], [f"{s_cat_pfx}expressions.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index(op.f('ix_catalog_manifestations_barcode'), 'manifestations', ['barcode'], unique=False, schema=s_cat)
    op.create_index(op.f('ix_catalog_manifestations_ean'), 'manifestations', ['ean'], unique=False, schema=s_cat)
    op.create_index(op.f('ix_catalog_manifestations_format'), 'manifestations', ['format'], unique=False, schema=s_cat)
    op.create_index(op.f('ix_catalog_manifestations_isbn13'), 'manifestations', ['isbn13'], unique=True, schema=s_cat)
    op.create_index(op.f('ix_catalog_manifestations_upc'), 'manifestations', ['upc'], unique=False, schema=s_cat)
    op.create_index('ix_manifestations_fts', 'manifestations', ['fts_simple'], unique=False, schema=s_cat, postgresql_using='gin')
    op.create_table('feedback_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_item_id'], [f"{s_soc_pfx}feedback_items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_soc
    )
    op.create_index(op.f('ix_social_feedback_comments_feedback_item_id'), 'feedback_comments', ['feedback_item_id'], unique=False, schema=s_soc)
    op.create_index(op.f('ix_social_feedback_comments_user_id'), 'feedback_comments', ['user_id'], unique=False, schema=s_soc)
    op.create_table('image_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_table('manifestation_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], [f"{s_cat_pfx}contributors.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index('ix_manifestation_contributions_contributor_id', 'manifestation_contributions', ['contributor_id'], unique=False, schema=s_cat)
    op.create_index('ix_manifestation_contributions_manifestation_id', 'manifestation_contributions', ['manifestation_id'], unique=False, schema=s_cat)
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('manifestation_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_id'], [f"{s_cat_pfx}reading_roadmaps.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('collection_status', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('lent_to_user_id', sa.UUID(), nullable=True),
    sa.Column('lent_to_name', sa.String(length=255), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lent_to_user_id'], [f"{s_auth_pfx}users.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_items_lent_to_user_id'), 'items', ['lent_to_user_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_items_owner_id'), 'items', ['owner_id'], unique=False, schema=s_inv)
    op.create_table('scan_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('format_hint', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=True),
    sa.Column('raw_request_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_scan_telemetry_barcode'), 'scan_telemetry', ['barcode'], unique=False, schema=s_inv)
    op.create_table('container_aggregations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_work_id', sa.Integer(), nullable=False),
    sa.Column('aggregated_type', sa.String(length=50), nullable=False),
    sa.Column('aggregated_work_id', sa.Integer(), nullable=True),
    sa.Column('aggregated_item_id', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.CheckConstraint("(aggregated_type = 'work' AND aggregated_work_id IS NOT NULL AND aggregated_item_id IS NULL) OR (aggregated_type = 'item' AND aggregated_item_id IS NOT NULL AND aggregated_work_id IS NULL)", name='ck_container_aggregation_type_match'),
    sa.ForeignKeyConstraint(['aggregated_item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['aggregated_work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['container_work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_cat
    )
    op.create_index('ix_container_aggregations_container_work_id', 'container_aggregations', ['container_work_id'], unique=False, schema=s_cat)
    op.create_table('escalation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.Column('manifestation_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('suggested_value', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'duplicate')", name='chk_escalation_status_valid'),
    sa.CheckConstraint('(case when work_id is not null then 1 else 0 end + case when expression_id is not null then 1 else 0 end + case when manifestation_id is not null then 1 else 0 end + case when item_id is not null then 1 else 0 end) <= 1', name='chk_escalation_target_exactly_one'),
    sa.ForeignKeyConstraint(['expression_id'], [f"{s_cat_pfx}expressions.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], [f"{s_auth_pfx}users.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_escalation_requests_expression_id'), 'escalation_requests', ['expression_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_escalation_requests_item_id'), 'escalation_requests', ['item_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_escalation_requests_manifestation_id'), 'escalation_requests', ['manifestation_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_escalation_requests_status'), 'escalation_requests', ['status'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_escalation_requests_user_id'), 'escalation_requests', ['user_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_escalation_requests_work_id'), 'escalation_requests', ['work_id'], unique=False, schema=s_inv)
    op.create_table('item_custody_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], [f"{s_auth_pfx}users.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index('ix_item_custody_events_item_id', 'item_custody_events', ['item_id'], unique=False, schema=s_inv)
    op.create_index('ix_item_custody_events_recorded_at', 'item_custody_events', ['recorded_at'], unique=False, schema=s_inv)
    op.create_table('item_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_table('item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], [f"{s_auth_pfx}users.id"], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], [f"{s_cat_pfx}tags.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_item_tags_item_id'), 'item_tags', ['item_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_item_tags_tag_id'), 'item_tags', ['tag_id'], unique=False, schema=s_inv)
    op.create_table('loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_loan_requests_item_id'), 'loan_requests', ['item_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_loan_requests_requester_id'), 'loan_requests', ['requester_id'], unique=False, schema=s_inv)
    op.create_table('social_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.Column('manifestation_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(case when work_id is not null then 1 else 0 end + case when expression_id is not null then 1 else 0 end + case when manifestation_id is not null then 1 else 0 end + case when item_id is not null then 1 else 0 end) = 1', name='chk_feedback_target_exactly_one'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='chk_feedback_rating_range'),
    sa.ForeignKeyConstraint(['expression_id'], [f"{s_cat_pfx}expressions.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'expression_id', name='uq_user_expression_feedback'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item_feedback'),
    sa.UniqueConstraint('user_id', 'manifestation_id', name='uq_user_manifestation_feedback'),
    sa.UniqueConstraint('user_id', 'work_id', name='uq_user_work_feedback'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_social_feedbacks_expression_id'), 'social_feedbacks', ['expression_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_feedbacks_item_id'), 'social_feedbacks', ['item_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_feedbacks_manifestation_id'), 'social_feedbacks', ['manifestation_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_feedbacks_user_id'), 'social_feedbacks', ['user_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_feedbacks_work_id'), 'social_feedbacks', ['work_id'], unique=False, schema=s_inv)
    op.create_table('social_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.Column('manifestation_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(case when work_id is not null then 1 else 0 end + case when expression_id is not null then 1 else 0 end + case when manifestation_id is not null then 1 else 0 end + case when item_id is not null then 1 else 0 end) = 1', name='chk_note_target_exactly_one'),
    sa.ForeignKeyConstraint(['expression_id'], [f"{s_cat_pfx}expressions.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manifestation_id'], [f"{s_cat_pfx}manifestations.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f"{s_auth_pfx}users.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], [f"{s_cat_pfx}works.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_social_notes_expression_id'), 'social_notes', ['expression_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_notes_item_id'), 'social_notes', ['item_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_notes_manifestation_id'), 'social_notes', ['manifestation_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_notes_user_id'), 'social_notes', ['user_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_social_notes_work_id'), 'social_notes', ['work_id'], unique=False, schema=s_inv)
    op.create_table('user_collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], [f"{s_inv_pfx}user_collections.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], [f"{s_inv_pfx}items.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=s_inv
    )
    op.create_index(op.f('ix_inventory_user_collection_items_collection_id'), 'user_collection_items', ['collection_id'], unique=False, schema=s_inv)
    op.create_index(op.f('ix_inventory_user_collection_items_item_id'), 'user_collection_items', ['item_id'], unique=False, schema=s_inv)
    # ### end Alembic commands ###

def downgrade():
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    s_auth = "auth" if is_pg else None
    s_cat = "catalog" if is_pg else None
    s_inv = "inventory" if is_pg else None
    s_soc = "social" if is_pg else None

# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_user_collection_items_item_id'), table_name='user_collection_items', schema=s_inv)
    op.drop_index(op.f('ix_inventory_user_collection_items_collection_id'), table_name='user_collection_items', schema=s_inv)
    op.drop_table('user_collection_items', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_notes_work_id'), table_name='social_notes', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_notes_user_id'), table_name='social_notes', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_notes_manifestation_id'), table_name='social_notes', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_notes_item_id'), table_name='social_notes', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_notes_expression_id'), table_name='social_notes', schema=s_inv)
    op.drop_table('social_notes', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_feedbacks_work_id'), table_name='social_feedbacks', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_feedbacks_user_id'), table_name='social_feedbacks', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_feedbacks_manifestation_id'), table_name='social_feedbacks', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_feedbacks_item_id'), table_name='social_feedbacks', schema=s_inv)
    op.drop_index(op.f('ix_inventory_social_feedbacks_expression_id'), table_name='social_feedbacks', schema=s_inv)
    op.drop_table('social_feedbacks', schema=s_inv)
    op.drop_index(op.f('ix_inventory_loan_requests_requester_id'), table_name='loan_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_loan_requests_item_id'), table_name='loan_requests', schema=s_inv)
    op.drop_table('loan_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_item_tags_tag_id'), table_name='item_tags', schema=s_inv)
    op.drop_index(op.f('ix_inventory_item_tags_item_id'), table_name='item_tags', schema=s_inv)
    op.drop_table('item_tags', schema=s_inv)
    op.drop_table('item_status_logs', schema=s_inv)
    op.drop_index('ix_item_custody_events_recorded_at', table_name='item_custody_events', schema=s_inv)
    op.drop_index('ix_item_custody_events_item_id', table_name='item_custody_events', schema=s_inv)
    op.drop_table('item_custody_events', schema=s_inv)
    op.drop_index(op.f('ix_inventory_escalation_requests_work_id'), table_name='escalation_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_escalation_requests_user_id'), table_name='escalation_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_escalation_requests_status'), table_name='escalation_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_escalation_requests_manifestation_id'), table_name='escalation_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_escalation_requests_item_id'), table_name='escalation_requests', schema=s_inv)
    op.drop_index(op.f('ix_inventory_escalation_requests_expression_id'), table_name='escalation_requests', schema=s_inv)
    op.drop_table('escalation_requests', schema=s_inv)
    op.drop_index('ix_container_aggregations_container_work_id', table_name='container_aggregations', schema=s_cat)
    op.drop_table('container_aggregations', schema=s_cat)
    op.drop_index(op.f('ix_inventory_scan_telemetry_barcode'), table_name='scan_telemetry', schema=s_inv)
    op.drop_table('scan_telemetry', schema=s_inv)
    op.drop_index(op.f('ix_inventory_items_owner_id'), table_name='items', schema=s_inv)
    op.drop_index(op.f('ix_inventory_items_lent_to_user_id'), table_name='items', schema=s_inv)
    op.drop_table('items', schema=s_inv)
    op.drop_table('roadmap_items', schema=s_cat)
    op.drop_index('ix_manifestation_contributions_manifestation_id', table_name='manifestation_contributions', schema=s_cat)
    op.drop_index('ix_manifestation_contributions_contributor_id', table_name='manifestation_contributions', schema=s_cat)
    op.drop_table('manifestation_contributions', schema=s_cat)
    op.drop_table('image_scans', schema=s_cat)
    op.drop_index(op.f('ix_social_feedback_comments_user_id'), table_name='feedback_comments', schema=s_soc)
    op.drop_index(op.f('ix_social_feedback_comments_feedback_item_id'), table_name='feedback_comments', schema=s_soc)
    op.drop_table('feedback_comments', schema=s_soc)
    op.drop_index('ix_manifestations_fts', table_name='manifestations', schema=s_cat, postgresql_using='gin')
    op.drop_index(op.f('ix_catalog_manifestations_upc'), table_name='manifestations', schema=s_cat)
    op.drop_index(op.f('ix_catalog_manifestations_isbn13'), table_name='manifestations', schema=s_cat)
    op.drop_index(op.f('ix_catalog_manifestations_format'), table_name='manifestations', schema=s_cat)
    op.drop_index(op.f('ix_catalog_manifestations_ean'), table_name='manifestations', schema=s_cat)
    op.drop_index(op.f('ix_catalog_manifestations_barcode'), table_name='manifestations', schema=s_cat)
    op.drop_table('manifestations', schema=s_cat)
    op.drop_index('ix_expression_contributions_expression_id', table_name='expression_contributions', schema=s_cat)
    op.drop_index('ix_expression_contributions_contributor_id', table_name='expression_contributions', schema=s_cat)
    op.drop_table('expression_contributions', schema=s_cat)
    op.drop_index(op.f('ix_social_feedback_items_user_id'), table_name='feedback_items', schema=s_soc)
    op.drop_index(op.f('ix_social_feedback_items_status'), table_name='feedback_items', schema=s_soc)
    op.drop_table('feedback_items', schema=s_soc)
    op.drop_index(op.f('ix_inventory_user_work_intents_work_id'), table_name='user_work_intents', schema=s_inv)
    op.drop_index(op.f('ix_inventory_user_work_intents_user_id'), table_name='user_work_intents', schema=s_inv)
    op.drop_table('user_work_intents', schema=s_inv)
    op.drop_index(op.f('ix_inventory_user_collections_parent_id'), table_name='user_collections', schema=s_inv)
    op.drop_index(op.f('ix_inventory_user_collections_owner_id'), table_name='user_collections', schema=s_inv)
    op.drop_table('user_collections', schema=s_inv)
    op.drop_table('shared_collections', schema=s_inv)
    op.drop_index('ix_entity_audit_logs_logged_at', table_name='entity_audit_logs', schema=s_inv)
    op.drop_index('ix_entity_audit_logs_entity', table_name='entity_audit_logs', schema=s_inv)
    op.drop_table('entity_audit_logs', schema=s_inv)
    op.drop_index('ix_work_parts_part_work_id', table_name='work_parts', schema=s_cat)
    op.drop_index('ix_work_parts_container_work_id', table_name='work_parts', schema=s_cat)
    op.drop_table('work_parts', schema=s_cat)
    op.drop_index('ix_work_expansion_links_expansion_work_id', table_name='work_expansion_links', schema=s_cat)
    op.drop_index('ix_work_expansion_links_base_work_id', table_name='work_expansion_links', schema=s_cat)
    op.drop_table('work_expansion_links', schema=s_cat)
    op.drop_index('ix_work_contributions_work_id', table_name='work_contributions', schema=s_cat)
    op.drop_index('ix_work_contributions_contributor_id', table_name='work_contributions', schema=s_cat)
    op.drop_table('work_contributions', schema=s_cat)
    op.drop_table('reading_roadmaps', schema=s_cat)
    op.drop_index(op.f('ix_catalog_expressions_kind'), table_name='expressions', schema=s_cat)
    op.drop_table('expressions', schema=s_cat)
    op.drop_table('user_roles', schema=s_auth)
    op.drop_index(op.f('ix_auth_user_consents_consent_type'), table_name='user_consents', schema=s_auth)
    op.drop_table('user_consents', schema=s_auth)
    op.drop_table('role_permissions', schema=s_auth)
    op.drop_table('metadata_refetch_log', schema=s_inv)
    op.drop_index('ix_llm_telemetry_provider_user_op_time', table_name='llm_telemetry', schema=s_inv)
    op.drop_table('llm_telemetry', schema=s_inv)
    op.drop_index(op.f('ix_catalog_instance_settings_key'), table_name='instance_settings', schema=s_cat)
    op.drop_table('instance_settings', schema=s_cat)
    op.drop_index('ix_works_search_vector', table_name='works', schema=s_cat, postgresql_using='gin')
    op.drop_index('ix_works_fts', table_name='works', schema=s_cat, postgresql_using='gin')
    op.drop_index(op.f('ix_catalog_works_sort_title'), table_name='works', schema=s_cat)
    op.drop_table('works', schema=s_cat)
    op.drop_index(op.f('ix_catalog_tags_name'), table_name='tags', schema=s_cat)
    op.drop_table('tags', schema=s_cat)
    op.drop_index(op.f('ix_catalog_contributors_name'), table_name='contributors', schema=s_cat)
    op.drop_table('contributors', schema=s_cat)
    op.drop_index(op.f('ix_catalog_boardgame_mechanics_bgg_id'), table_name='boardgame_mechanics', schema=s_cat)
    op.drop_table('boardgame_mechanics', schema=s_cat)
    op.drop_index(op.f('ix_auth_users_public_username'), table_name='users', schema=s_auth)
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema=s_auth)
    op.drop_table('users', schema=s_auth)
    op.drop_index(op.f('ix_auth_token_blocklist_jti'), table_name='token_blocklist', schema=s_auth)
    op.drop_table('token_blocklist', schema=s_auth)
    op.drop_index(op.f('ix_auth_roles_name'), table_name='roles', schema=s_auth)
    op.drop_table('roles', schema=s_auth)
    op.drop_index(op.f('ix_auth_permissions_name'), table_name='permissions', schema=s_auth)
    op.drop_table('permissions', schema=s_auth)
    # ### end Alembic commands ###
