#!/usr/bin/env python3
# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
"""Generator script for iqoqo media taxonomy.

Reads shared/taxonomy.yaml and generates Python, TypeScript, and Turtle outputs.
"""

import json
from pathlib import Path

import yaml

ROOT_DIR = Path(__file__).resolve().parents[1]
YAML_FILE = ROOT_DIR / "shared" / "taxonomy.yaml"

PY_OUT = ROOT_DIR / "app" / "core" / "taxonomy.py"
TS_OUT = ROOT_DIR / "frontend" / "types" / "taxonomy.ts"
TTL_OUT = ROOT_DIR / "docs" / "ontology" / "taxonomy.ttl"

COPYRIGHT_HEADER = """# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
# THIS FILE IS AUTO-GENERATED by scripts/generate_taxonomy.py
# DO NOT EDIT MANUALLY. Update shared/taxonomy.yaml instead.
"""


def generate_python(data: dict) -> str:
    py_code = [COPYRIGHT_HEADER, ""]

    # Categories
    py_code.append("class MediaCategory:")
    for cat in data["media_categories"]:
        py_code.append(f'    {cat.upper()} = "{cat}"')
    py_code.append(f'    ALL = ({", ".join(f"{repr(c)}" for c in data["media_categories"])})\n')

    # Formats
    py_code.append("class MediaFormat:")
    all_formats = []
    format_to_category = {}
    for cat, info in data["media_categories"].items():
        for fmt in info["formats"]:
            fmt_id = fmt["id"]
            all_formats.append(f'"{fmt_id}"')
            format_to_category[fmt_id] = cat

            # Ensure valid Python identifier
            const_name = fmt_id.upper()
            if const_name[0].isdigit():
                const_name = f"F_{const_name}"

            py_code.append(f'    {const_name} = "{fmt_id}"')
    py_code.append(f'    ALL = ({", ".join(all_formats)})\n')

    # Statuses
    coll_statuses = [s["id"] for s in data["collection_statuses"]]
    py_code.append(f'COLLECTION_STATUSES: tuple[str, ...] = ({", ".join(repr(s) for s in coll_statuses)})\n')

    prog_statuses = set()
    for statuses in data["progress_statuses"].values():
        prog_statuses.update(statuses)
    py_code.append(f'PROGRESS_STATUSES: tuple[str, ...] = ({", ".join(repr(s) for s in sorted(prog_statuses))})\n')

    # Maps
    py_code.append("CATEGORY_PROGRESS_STATUSES: dict[str, tuple[str, ...]] = {")
    for cat, statuses in data["progress_statuses"].items():
        py_code.append(f'    "{cat}": {tuple(statuses)},')
    py_code.append("}\n")

    py_code.append(f"FORMAT_TO_CATEGORY: dict[str, str] = {json.dumps(format_to_category, indent=4)}\n")

    # Image Types
    image_types_map = {cat: info.get("image_types", []) for cat, info in data["media_categories"].items()}
    py_code.append(f'GLOBAL_IMAGE_TYPES: list[str] = {json.dumps(data["global_image_types"])}')
    py_code.append(f"CATEGORY_IMAGE_TYPES: dict[str, list[str]] = {json.dumps(image_types_map, indent=4)}\n")

    # Scan Formats
    py_code.append(f'SCAN_FORMATS: tuple[str, ...] = {tuple(data["scan_formats"])}\n')

    return "\n".join(py_code)


def generate_typescript(data: dict) -> str:
    ts_header = COPYRIGHT_HEADER.replace("#", "//").replace("// THIS FILE", "\n// THIS FILE")
    ts_code = [ts_header, ""]

    all_formats = []
    for _cat, info in data["media_categories"].items():
        for fmt in info["formats"]:
            all_formats.append(fmt["id"])

    ts_code.append(f"export const MEDIA_FORMATS = {json.dumps(all_formats)} as const;")
    ts_code.append("export type MediaFormat = (typeof MEDIA_FORMATS)[number];\n")

    ts_code.append(f"export const MEDIA_CATEGORIES = {json.dumps(list(data['media_categories'].keys()))} as const;")
    ts_code.append("export type MediaCategory = (typeof MEDIA_CATEGORIES)[number];\n")

    ts_code.append(f"export const MEDIA_HIERARCHY = {json.dumps(data['media_categories'], indent=2)} as const;\n")
    ts_code.append(f"export const CATEGORY_STATUS_MAP = {json.dumps(data['progress_statuses'], indent=2)} as const;\n")

    ts_code.append(f"export const SCAN_FORMATS = {json.dumps(data['scan_formats'])} as const;")
    ts_code.append("export type ScanFormat = (typeof SCAN_FORMATS)[number];\n")

    ts_code.append(f"export const GLOBAL_IMAGE_TYPES = {json.dumps(data['global_image_types'])} as const;")

    cat_image_types = {cat: info.get("image_types", []) for cat, info in data["media_categories"].items()}
    ts_code.append(f"export const CATEGORY_IMAGE_TYPES = {json.dumps(cat_image_types, indent=2)} as const;\n")

    all_image_types = set(data["global_image_types"])
    for types in cat_image_types.values():
        all_image_types.update(types)

    # Status types
    coll_statuses = [s["id"] for s in data["collection_statuses"]]
    coll_types = " | ".join(f'"{s}"' for s in sorted(coll_statuses))
    ts_code.append(f"export type CollectionStatus = {coll_types};\n")

    prog_statuses_set = set()
    for statuses in data["progress_statuses"].values():
        prog_statuses_set.update(statuses)
    prog_types = " | ".join(f'"{s}"' for s in sorted(prog_statuses_set))
    ts_code.append(f"export type ProgressStatus = {prog_types};\n")

    image_types = " | ".join(f'"{t}"' for t in sorted(all_image_types))
    ts_code.append(f"export type ImageType = {image_types};\n")

    return "\n".join(ts_code)


def generate_turtle(data: dict) -> str:
    ttl_code = [
        COPYRIGHT_HEADER.replace("#", "#"),
        "@prefix : <https://iqoqo.org/ontology#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "",
        "# AUTO-GENERATED from shared/taxonomy.yaml",
        "",
    ]

    for cat, info in data["media_categories"].items():
        cat_class = f"MediaCategory{cat.replace('_', ' ').title().replace(' ', '')}"
        ttl_code.append(f":{cat_class} a :MediaCategory ;")
        ttl_code.append(f'    rdfs:label "{cat}" ;')
        ttl_code.append(f'    rdfs:comment "{info["label"]}" .')

        for fmt in info["formats"]:
            fmt_class = f"MediaFormat{fmt['id'].replace('_', ' ').title().replace(' ', '')}"
            ttl_code.append(f":{fmt_class} a :MediaFormat ;")
            ttl_code.append(f'    rdfs:label "{fmt["id"]}" ;')
            ttl_code.append(f'    rdfs:comment "{fmt["label"]}" .')

    ttl_code.append("")

    # Collection Statuses
    for status in data["collection_statuses"]:
        status_class = f"Status{status['id'].replace('_', ' ').title().replace(' ', '')}"
        ttl_code.append(f":{status_class} a :CollectionStatus ; rdfs:label \"{status['id']}\" .")

    ttl_code.append("")

    # Progress Statuses
    for cat, statuses in data["progress_statuses"].items():
        cat_class = f"MediaCategory{cat.replace('_', ' ').title().replace(' ', '')}"
        for status in statuses:
            status_class = f"Status{status.replace('_', ' ').title().replace(' ', '')}"
            ttl_code.append(f':{status_class} a :ProgressStatus ; rdfs:label "{status}" ; :applicableToCategory :{cat_class} .')

    ttl_code.append("")
    return "\n".join(ttl_code)


if __name__ == "__main__":
    with open(YAML_FILE) as f:
        data = yaml.safe_load(f)

    PY_OUT.write_text(generate_python(data))
    TS_OUT.write_text(generate_typescript(data))
    TTL_OUT.write_text(generate_turtle(data))
    print("Taxonomy generated successfully.")
