#!/usr/bin/env python3
"""
Simple permissions sync script for development.
Reads shared/permissions.yaml and emits app/core/permissions.py and frontend/types/permissions.ts
"""

# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = ROOT / "shared" / "permissions.yaml"
PY_OUT = ROOT / "app" / "core" / "permissions.py"

# Must match [tool.black].line-length in pyproject.toml. The generated module is
# checked by `black --check` in CI, so the generator has to emit already-formatted
# output or every run leaves the tree dirty.
BLACK_LINE_LENGTH = 140
TS_OUT = ROOT / "frontend" / "lib" / "permissions.ts"


def get_functional_content(text: str) -> str:
    """Helper to strip comments for comparison."""
    return "\n".join(line for line in text.splitlines() if line.strip() and not line.strip().startswith(("#", "//", "/*", "*/", "*")))


def main() -> None:
    """Main execution function."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true", help="Verify generated files match YAML")
    args = parser.parse_args()

    if not YAML_PATH.exists():
        print(f"Permissions YAML not found: {YAML_PATH}")
        sys.exit(1)

    with open(YAML_PATH, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    permissions = [p["name"] for p in data.get("permissions", [])]

    # MOD-OPS-13: role definitions move out of scripts/sync_db_permissions.py
    # and into this generated module, so exactly one place answers "which
    # permissions does role X get". The YAML section is the Single Source of
    # Truth; this module is its generated, importable form.
    roles = data.get("roles", [])

    # Generate Python Enum
    members = []
    for name in permissions:
        key = name.upper().replace(":", "_").replace("-", "_")
        members.append((key, name))

    role_members = []
    for role in roles:
        role_name = role["name"]
        key = role_name.upper().replace(":", "_").replace("-", "_")
        role_members.append((key, role_name, role.get("permissions", []), bool(role.get("protected", False))))

    py_lines = [
        "# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)",
        "#",
        "# This program is free software: you can redistribute it and/or modify",
        "# it under the terms of the GNU Affero General Public License as published",
        "# by the Free Software Foundation, either version 3 of the License, or",
        "# (at your option) any later version.",
        "#",
        "# This program is distributed in the hope that it will be useful,",
        "# but WITHOUT ANY WARRANTY; without even the implied warranty of",
        "# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the",
        "# GNU Affero General Public License for more details.",
        "#",
        "# You should have received a copy of the GNU Affero General Public License",
        "# along with this program.  If not, see <https://www.gnu.org/licenses/>",
        "#",
        "# Auto-generated by scripts/sync_permissions.py -- DO NOT EDIT BY HAND.",
        "# Edit shared/permissions.yaml and run `make sync-permissions` instead.",
        '"""Generated permission vocabulary and role-to-permission resolution.',
        "",
        "Auto-generated from shared/permissions.yaml by",
        "scripts/sync_db_permissions.py. Edit that file, not this one; changes here are",
        "overwritten.",
        '"""',
        # Black separates a module docstring from the first statement with a
        # blank line. Emitting it here keeps the generated file black-stable,
        # which tests/test_role_definitions.py asserts.
        "",
        "from collections.abc import Iterable",
        "from enum import StrEnum",
        "from fnmatch import fnmatchcase",
        "",
        # Two blank lines before the first class: isort/ruff enforce this, and
        # emitting one makes `make lint-python` fail on a freshly generated file.
        "",
        "class PermissionName(StrEnum):",
    ]
    for k, v in members:
        py_lines.append(f'    {k} = "{v}"')

    py_lines.append("")
    py_lines.append("")
    py_lines.append("class RoleName(StrEnum):")
    py_lines.append('    """Built-in roles seeded by `scripts/sync_db_permissions.py`."""')
    py_lines.append("")
    for k, v, _patterns, _protected in role_members:
        py_lines.append(f'    {k} = "{v}"')

    py_lines.append("")
    py_lines.append("")
    py_lines.append("# Permission grants per role, as shell-style globs over permission names.")
    py_lines.append('# `"*"` means every permission present in the instance, including any an')
    py_lines.append("# administrator added by hand. Patterns are resolved at sync time by")
    py_lines.append("# `resolve_role_permissions` against the permissions actually in the database,")
    py_lines.append("# so a permission missing from permissions.yaml is still granted where it matches.")
    py_lines.append("ROLE_PERMISSION_PATTERNS: dict[str, tuple[str, ...]] = {")
    for k, _v, patterns, _protected in role_members:
        # Always emit a trailing comma: a single-element tuple needs one, and
        # black would otherwise reformat this line on the next format run,
        # making `--verify` fail on an unchanged YAML.
        rendered = ", ".join(f'"{pat}"' for pat in patterns)
        # Two distinct commas are required and easy to confuse:
        #   * inside the parens -- with a single pattern `(x)` is a plain str,
        #     not a 1-tuple, and the generated module fails to import;
        #   * after the closing paren -- without it Python parses two adjacent
        #     dict entries as one expression and raises SyntaxError.
        if not patterns:
            py_lines.append(f"    RoleName.{k}: (),")
            continue
        # A single-element tuple REQUIRES the comma (`(x)` would be a str), and
        # black leaves that on one line when it fits. A multi-element tuple must
        # NOT carry a trailing comma: that is black's "magic trailing comma",
        # which forces the collection to explode even when it would fit. So the
        # two cases are emitted differently on purpose.
        # `rendered` is already comma-joined with no trailing comma; a
        # single-element tuple needs the comma added explicitly.
        joined = f'"{patterns[0]}",' if len(patterns) == 1 else rendered
        single_line = f"    RoleName.{k}: ({joined}),"
        if len(single_line) <= BLACK_LINE_LENGTH:
            py_lines.append(single_line)
        else:
            # Black would explode any line longer than the configured limit, so
            # emit it already exploded. Without this, `black` rewrites the
            # generated file, the next generator run produces different output,
            # and `sync_permissions.py --verify` fails on a YAML that did not
            # change at all. The magic trailing comma keeps black from
            # collapsing it back.
            py_lines.append(f"    RoleName.{k}: (")
            for pattern in patterns:
                py_lines.append(f'        "{pattern}",')
            py_lines.append("    ),")
    py_lines.append("}")
    py_lines.append("")
    py_lines.append("# Roles that must never be deleted through the admin API.")
    # Sorted so an unchanged YAML always produces an identical file; otherwise
    # `sync_permissions.py --verify` would flap on ordering alone.
    protected = sorted(v for _k, v, _p, prot in role_members if prot)
    rendered_protected = ", ".join(f'"{r}"' for r in protected)
    py_lines.append("PROTECTED_ROLE_NAMES: frozenset[str] = frozenset({" + rendered_protected + "})")
    py_lines.append("")
    py_lines.append("")
    py_lines.append("def resolve_role_permissions(role: str, permission_names: Iterable[str]) -> set[str]:")
    py_lines.append('    """Expand a role\'s globs against the permission names present in this instance.')
    py_lines.append("")
    py_lines.append("    Args:")
    py_lines.append("        role: Role name, case-insensitive.")
    py_lines.append("        permission_names: Every permission name known to the instance.")
    py_lines.append("")
    py_lines.append("    Returns:")
    py_lines.append("        The subset of `permission_names` granted to `role`.")
    py_lines.append('    """')
    # `role` may arrive as a RoleName (a StrEnum, so str() gives its value) or
    # as a plain string; normalise both to the stored lowercase form.
    py_lines.append("    patterns = ROLE_PERMISSION_PATTERNS.get(str(role).lower())")
    py_lines.append("    if patterns is None:")
    py_lines.append("        return set()")
    py_lines.append("    names = list(permission_names)")
    py_lines.append('    if "*" in patterns:')
    py_lines.append("        return set(names)")
    py_lines.append("    # fnmatchcase, not fnmatch: matching must not depend on the host OS, or a")
    py_lines.append("    # role grant could differ between a developer laptop and a Linux server.")
    py_lines.append("    return {name for name in names if any(fnmatchcase(name, pattern) for pattern in patterns)}")

    py_text = "\n".join(py_lines) + "\n"

    # Generate TS
    ts_lines = [
        "// Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)",
        "//",
        "// This program is free software: you can redistribute it and/or modify",
        "// it under the terms of the GNU Affero General Public License as published",
        "// by the Free Software Foundation, either version 3 of the License, or",
        "// (at your option) any later version.",
        "//",
        "// This program is distributed in the hope that it will be useful,",
        "// but WITHOUT ANY WARRANTY; without even the implied warranty of",
        "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the",
        "// GNU Affero General Public License for more details.",
        "//",
        "// You should have received a copy of the GNU Affero General Public License",
        "// along with this program.  If not, see <https://www.gnu.org/licenses/>",
        "//",
        "// Auto-generated by scripts/sync_permissions.py",
        "/**",
        " * Enumeration of all system permissions.",
        " * Must be kept in sync with shared/permissions.yaml.",
        " */",
        "export enum PermissionName {",
    ]
    for k, v in members:
        ts_lines.append(f'  {k} = "{v}",')

    ts_lines.append("}\n")

    if args.verify:
        ok = True
        # Verify Python
        if PY_OUT.exists():
            if get_functional_content(PY_OUT.read_text(encoding="utf-8")) != get_functional_content(py_text):
                print(f"Mismatch in {PY_OUT}")
                ok = False

        # Verify TS
        ts_text = "\n".join(ts_lines) + "\n"
        if TS_OUT.exists():
            if get_functional_content(TS_OUT.read_text(encoding="utf-8")) != get_functional_content(ts_text):
                print(f"Mismatch in {TS_OUT}")
                ok = False

        if not ok:
            sys.exit(2)
        print("Permissions are in sync.")
        sys.exit(0)

    # Write files
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.write_text(py_text, encoding="utf-8")
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text("\n".join(ts_lines) + "\n", encoding="utf-8")

    print(f"Successfully synced {PY_OUT} and {TS_OUT}")


if __name__ == "__main__":
    main()
