# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#

name: Release and Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    # Only run if the PR was merged (not just closed) AND the branch started with 'release/'
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(python scripts/extract_version.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract Release Notes from CHANGELOG
        id: extract_notes
        run: |
          python scripts/extract_changelog.py ${{ env.VERSION }} > release_notes.md

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Backend Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/iqoqo-backend:latest
            ghcr.io/${{ github.repository_owner }}/iqoqo-backend:${{ env.VERSION }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/iqoqo-backend-buildcache:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/iqoqo-backend-buildcache:cache,mode=max,ignore-error=true

      - name: Build and push Frontend Image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/iqoqo-frontend:latest
            ghcr.io/${{ github.repository_owner }}/iqoqo-frontend:${{ env.VERSION }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/iqoqo-frontend-buildcache:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/iqoqo-frontend-buildcache:cache,mode=max,ignore-error=true

      - name: Create GitHub Release and Tag
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
