# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
# Auto-generated by scripts/sync_permissions.py -- DO NOT EDIT BY HAND.
# Edit shared/permissions.yaml and run `make sync-permissions` instead.
from collections.abc import Iterable
from enum import StrEnum
from fnmatch import fnmatchcase


class PermissionName(StrEnum):
    CONFIG_AFFILIATE = "config:affiliate"
    CONFIG_EXTERNAL_APIS = "config:external_apis"
    CONFIG_FEDERATION = "config:federation"
    CONFIG_INTERNAL = "config:internal"
    DELETE_ITEM = "delete:item"
    DELETE_MANIFESTATION = "delete:manifestation"
    EDIT_COVER = "edit:cover"
    ESCALATE_REQUEST = "escalate:request"
    ESCALATE_RESOLVE = "escalate:resolve"
    LLM_GENERATE_CLOUD = "llm_generate:cloud"
    LLM_GENERATE_COVER = "llm_generate:cover"
    LLM_GENERATE_METADATA = "llm_generate:metadata"
    READ_METADATA = "read:metadata"
    READ_OWNERS = "read:owners"
    READ_ROLES = "read:roles"
    READ_USERS = "read:users"
    REFETCH_METADATA = "refetch:metadata"
    REFETCH_COVER = "refetch:cover"
    REGENERATE_COVER = "regenerate:cover"
    TICKETS_ADMIN = "tickets:admin"
    TICKETS_CREATOR = "tickets:creator"
    UPDATE_ITEM = "update:item"
    UPLOAD_COVER = "upload:cover"
    WRITE_ITEM = "write:item"
    WRITE_METADATA = "write:metadata"
    WRITE_ROLES = "write:roles"
    WRITE_USERS = "write:users"


class RoleName(StrEnum):
    """Built-in roles seeded by `scripts/sync_db_permissions.py`."""

    ADMIN = "admin"
    CONTRIBUTOR = "contributor"
    USER = "user"


# Permission grants per role, as shell-style globs over permission names.
# `"*"` means every permission present in the instance, including any an
# administrator added by hand. Patterns are resolved at sync time by
# `resolve_role_permissions` against the permissions actually in the database,
# so a permission missing from permissions.yaml is still granted where it matches.
ROLE_PERMISSION_PATTERNS: dict[str, tuple[str, ...]] = {
    RoleName.ADMIN: ("*",),
    RoleName.CONTRIBUTOR: ("*:metadata", "llm_generate:*", "edit:cover", "delete:item", "escalate:resolve"),
    RoleName.USER: (
        "write:item",
        "update:item",
        "delete:item",
        "read:metadata",
        "upload:cover",
        "regenerate:cover",
        "llm_generate:metadata",
        "llm_generate:cover",
        "escalate:request",
        "tickets:creator",
    ),
}

# Roles that must never be deleted through the admin API.
PROTECTED_ROLE_NAMES: frozenset[str] = frozenset({"admin", "contributor", "user"})


def resolve_role_permissions(role: str, permission_names: Iterable[str]) -> set[str]:
    """Expand a role's globs against the permission names present in this instance.

    Args:
        role: Role name, case-insensitive.
        permission_names: Every permission name known to the instance.

    Returns:
        The subset of `permission_names` granted to `role`.
    """
    patterns = ROLE_PERMISSION_PATTERNS.get(str(role).lower())
    if patterns is None:
        return set()
    names = list(permission_names)
    if "*" in patterns:
        return set(names)
    # fnmatchcase, not fnmatch: matching must not depend on the host OS, or a
    # role grant could differ between a developer laptop and a Linux server.
    return {name for name in names if any(fnmatchcase(name, pattern) for pattern in patterns)}
