# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
# THIS FILE IS AUTO-GENERATED by scripts/generate_taxonomy.py
# DO NOT EDIT MANUALLY. Update shared/taxonomy.yaml instead.


class MediaCategory:
    TEXT = "text"
    AUDIOBOOK = "audiobook"
    MUSIC = "music"
    MOVIE = "movie"
    BOARD_GAME = "board_game"
    PUZZLE = "puzzle"
    ALL = ("text", "audiobook", "music", "movie", "board_game", "puzzle")


class MediaFormat:
    BOOK = "book"
    GRAPHIC_NOVEL = "graphic_novel"
    COMIC_BOOK = "comic_book"
    MAGAZINE = "magazine"
    EBOOK = "ebook"
    AUDIOBOOK_CD = "audiobook_cd"
    AUDIOBOOK_CASSETTE = "audiobook_cassette"
    AUDIOBOOK_DIGITAL = "audiobook_digital"
    CD = "cd"
    VINYL = "vinyl"
    SACD = "sacd"
    CASSETTE = "cassette"
    MINIDISC = "minidisc"
    CD_DVD_COMBO = "cd_dvd_combo"
    DVD = "dvd"
    BLURAY = "bluray"
    F_4K_UHD = "4k_uhd"
    VCD = "vcd"
    VHS = "vhs"
    LASERDISC = "laserdisc"
    BOARD_GAME = "board_game"
    CARDS = "cards"
    RPG_MANUAL = "rpg_manual"
    MINIATURES = "miniatures"
    JIGSAW_PUZZLE = "jigsaw_puzzle"
    MECHANICAL_PUZZLE = "mechanical_puzzle"
    ALL = (
        "book",
        "graphic_novel",
        "comic_book",
        "magazine",
        "ebook",
        "audiobook_cd",
        "audiobook_cassette",
        "audiobook_digital",
        "cd",
        "vinyl",
        "sacd",
        "cassette",
        "minidisc",
        "cd_dvd_combo",
        "dvd",
        "bluray",
        "4k_uhd",
        "vcd",
        "vhs",
        "laserdisc",
        "board_game",
        "cards",
        "rpg_manual",
        "miniatures",
        "jigsaw_puzzle",
        "mechanical_puzzle",
    )


COLLECTION_STATUSES: tuple[str, ...] = ("wish_list", "ordered", "available", "lent", "damaged", "lost")

PROGRESS_STATUSES: tuple[str, ...] = (
    "dnf",
    "listened",
    "listening",
    "played",
    "playing",
    "read",
    "reading",
    "want_to_listen",
    "want_to_play",
    "want_to_read",
    "want_to_watch",
    "watched",
)

CATEGORY_PROGRESS_STATUSES: dict[str, tuple[str, ...]] = {
    "text": ("want_to_read", "reading", "read", "dnf"),
    "audiobook": ("want_to_listen", "listening", "listened", "dnf"),
    "music": ("want_to_listen", "listened"),
    "movie": ("want_to_watch", "watched", "dnf"),
    "board_game": ("want_to_play", "playing", "played"),
    "puzzle": ("want_to_play", "playing", "played"),
}

FORMAT_TO_CATEGORY: dict[str, str] = {
    "book": "text",
    "graphic_novel": "text",
    "comic_book": "text",
    "magazine": "text",
    "ebook": "text",
    "audiobook_cd": "audiobook",
    "audiobook_cassette": "audiobook",
    "audiobook_digital": "audiobook",
    "cd": "music",
    "vinyl": "music",
    "sacd": "music",
    "cassette": "music",
    "minidisc": "music",
    "cd_dvd_combo": "music",
    "dvd": "movie",
    "bluray": "movie",
    "4k_uhd": "movie",
    "vcd": "movie",
    "vhs": "movie",
    "laserdisc": "movie",
    "board_game": "board_game",
    "cards": "board_game",
    "rpg_manual": "board_game",
    "miniatures": "board_game",
    "jigsaw_puzzle": "puzzle",
    "mechanical_puzzle": "puzzle",
}

FORMAT_ALIAS_TO_CATEGORY: dict[str, str] = {
    "book": "text",
    "graphic_novel": "text",
    "comic_book": "text",
    "magazine": "text",
    "ebook": "text",
    "audiobook_cd": "audiobook",
    "audiobook_cassette": "audiobook",
    "audiobook_digital": "audiobook",
    "cd": "music",
    "vinyl": "music",
    "sacd": "music",
    "cassette": "music",
    "minidisc": "music",
    "cd_dvd_combo": "music",
    "dvd": "movie",
    "bluray": "movie",
    "4k_uhd": "movie",
    "vcd": "movie",
    "vhs": "movie",
    "laserdisc": "movie",
    "board_game": "board_game",
    "cards": "board_game",
    "rpg_manual": "board_game",
    "miniatures": "board_game",
    "jigsaw_puzzle": "puzzle",
    "mechanical_puzzle": "puzzle",
    "standard": "text",
    "audio": "music",
    "sound": "music",
    "lp": "music",
    "video": "movie",
    "moving image": "movie",
    "game": "board_game",
    "boardgame": "board_game",
    "three-dimensional object": "board_game",
}

GLOBAL_IMAGE_TYPES: list[str] = ["front", "back", "spine", "other"]
CATEGORY_IMAGE_TYPES: dict[str, list[str]] = {
    "text": ["dust_jacket", "slipcase", "pages"],
    "audiobook": ["disc", "cassette", "inlay", "slipcase"],
    "music": ["disc", "inlay", "vinyl_label", "gatefold", "obi", "booklet"],
    "movie": ["disc", "inlay", "slipcover", "booklet"],
    "board_game": ["box", "board", "components", "rulebook"],
    "puzzle": ["pieces", "completed_puzzle", "poster"],
}

CATEGORY_DEFAULT_IMAGE_TYPE: dict[str, str] = {
    "text": "front",
    "audiobook": "front",
    "music": "disc",
    "movie": "disc",
    "board_game": "box",
    "puzzle": "box",
}

SCAN_FORMATS: tuple[str, ...] = ("book", "audiobook", "music", "movie", "board_game", "puzzle")
